// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Active lists runs in progress (for a page opened mid-run).
 */
export function Active(): $CancellablePromise<$models.RunInfo[] | null> {
    return $Call.ByID(1266724997);
}

/**
 * Cancel stops a run: queued servers are not started and running commands
 * are killed. Cancelling a finished run does nothing.
 */
export function Cancel(runID: string): $CancellablePromise<void> {
    return $Call.ByID(928427565, runID);
}

/**
 * Check returns why a script looks dangerous (empty when it doesn't).
 */
export function Check(script: string): $CancellablePromise<$models.Danger[] | null> {
    return $Call.ByID(2149548733, script);
}

/**
 * DeleteHistory removes finished runs (all when id is "").
 */
export function DeleteHistory(id: string): $CancellablePromise<void> {
    return $Call.ByID(2525694208, id);
}

/**
 * DeleteSnippet removes a snippet.
 */
export function DeleteSnippet(id: string): $CancellablePromise<void> {
    return $Call.ByID(2047805005, id);
}

/**
 * GetRun returns a run (live state while running, else from history).
 */
export function GetRun(id: string): $CancellablePromise<$models.RunInfo> {
    return $Call.ByID(3020358122, id);
}

/**
 * History lists past runs, newest first (limit 1–500, default 50).
 */
export function History(limit: number): $CancellablePromise<$models.HistoryItem[] | null> {
    return $Call.ByID(1482322805, limit);
}

/**
 * Presets lists the predefined actions.
 */
export function Presets(): $CancellablePromise<$models.Preset[] | null> {
    return $Call.ByID(379148525);
}

/**
 * Preview resolves a spec without running anything (dry run).
 */
export function Preview(spec: $models.Spec): $CancellablePromise<$models.Preview> {
    return $Call.ByID(271866941, spec);
}

/**
 * PreviewRerun resolves what Rerun would do (for the confirmation dialog).
 */
export function PreviewRerun(runID: string, onlyFailed: boolean): $CancellablePromise<$models.Preview> {
    return $Call.ByID(1482888925, runID, onlyFailed);
}

/**
 * Render returns the script a preset runs with the given parameters.
 */
export function Render(preset: string, params: { [_ in string]?: string } | null): $CancellablePromise<$models.Rendered> {
    return $Call.ByID(4218643455, preset, params);
}

/**
 * Rerun starts a new run with the same spec, on every server or only on the
 * ones that did not succeed. Servers deleted since are left out.
 */
export function Rerun(runID: string, onlyFailed: boolean): $CancellablePromise<string> {
    return $Call.ByID(2672827963, runID, onlyFailed);
}

/**
 * Run validates spec and starts executing it in the background. Progress
 * arrives as command:update events and the end as command:finished.
 */
export function Run(spec: $models.Spec): $CancellablePromise<string> {
    return $Call.ByID(2424320620, spec);
}

/**
 * SaveSnippet creates (empty id) or updates a snippet.
 */
export function SaveSnippet($in: $models.Snippet): $CancellablePromise<$models.Snippet> {
    return $Call.ByID(2502254863, $in);
}

/**
 * Snippets lists saved commands, by name.
 */
export function Snippets(): $CancellablePromise<$models.Snippet[] | null> {
    return $Call.ByID(313264633);
}

/**
 * Targets lists saved servers with their readiness.
 */
export function Targets(): $CancellablePromise<$models.Target[] | null> {
    return $Call.ByID(165105863);
}
