// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apperr$0 from "../../internal/apperr/models.js";

/**
 * Danger is one reason a command looks destructive. Code is translated by
 * the frontend as "cmd.danger.<code>"; Match is the offending fragment.
 */
export interface Danger {
    "code": string;

    /**
     * danger | warn
     */
    "level": string;
    "match": string;
}

/**
 * FinishedEvent is the payload of command:finished.
 */
export interface FinishedEvent {
    "runId": string;
    "status": string;
    "summary": Summary;
    "finished": number;
}

/**
 * HistoryItem is a past run in the history list.
 */
export interface HistoryItem {
    "id": string;

    /**
     * command (first 200 chars) or preset id
     */
    "title": string;
    "kind": string;
    "preset": string;
    "snippet": string;
    "actor": string;
    "started": number;
    "finished": number;
    "status": string;
    "summary": Summary;
}

/**
 * Preset is a predefined action. Its title is "cmd.preset.<id>".
 */
export interface Preset {
    "id": string;

    /**
     * service | info | docker | power
     */
    "category": string;
    "params": PresetParam[] | null;

    /**
     * Sudo means the action needs root (sudo is forced on).
     */
    "sudo": boolean;

    /**
     * Danger marks actions that always need a typed confirmation.
     */
    "danger": boolean;
}

/**
 * PresetParam describes one input of a preset. Labels are translated by the
 * frontend as "cmd.preset.param.<name>".
 */
export interface PresetParam {
    "name": string;

    /**
     * unit | int | enum | bool
     */
    "kind": string;
    "required": boolean;
    "default": string;

    /**
     * enum values
     */
    "options": string[] | null;
    "min": number;
    "max": number;
}

/**
 * Preview is the dry-run view of a spec.
 */
export interface Preview {
    "command": string;
    "sudo": boolean;
    "timeoutSec": number;
    "concurrency": number;
    "dangers": Danger[] | null;

    /**
     * needs a typed confirmation
     */
    "danger": boolean;
    "servers": PreviewServer[] | null;
}

/**
 * PreviewServer is what would happen on one server.
 */
export interface PreviewServer {
    "serverId": string;
    "name": string;
    "environment": string;

    /**
     * Action: run | skip.
     */
    "action": string;

    /**
     * error code when skipped
     */
    "reason": string;
    "via": string;
    "sudo": string;

    /**
     * exactly what is executed
     */
    "command": string;
}

/**
 * Rendered is a preset turned into the shell script that will run.
 */
export interface Rendered {
    "command": string;
    "sudo": boolean;
    "danger": boolean;
}

/**
 * RunInfo is a whole run (live or from history).
 */
export interface RunInfo {
    "id": string;
    "spec": Spec;

    /**
     * resolved script
     */
    "command": string;

    /**
     * effective
     */
    "sudo": boolean;
    "actor": string;

    /**
     * unix ms
     */
    "started": number;

    /**
     * 0 while running
     */
    "finished": number;

    /**
     * running | done | failed | cancelled | interrupted
     */
    "status": string;
    "summary": Summary;
    "results": ServerResult[] | null;
    "dangers": Danger[] | null;
}

/**
 * ServerResult is the state of one server in a run; it is also the payload
 * of the command:update event.
 */
export interface ServerResult {
    "runId": string;
    "serverId": string;
    "name": string;
    "environment": string;
    "state": string;
    "exitCode": number;
    "stdout": string;
    "stderr": string;
    "truncated": boolean;
    "error": apperr$0.Error | null;

    /**
     * unix ms
     */
    "startedAt": number;

    /**
     * unix ms
     */
    "finishedAt": number;
}

/**
 * Snippet is a saved command.
 */
export interface Snippet {
    "id": string;
    "name": string;
    "command": string;
    "sudo": boolean;
    "description": string;
    "created": number;
    "updated": number;
}

/**
 * Spec describes what to run and where.
 */
export interface Spec {
    "servers": string[] | null;

    /**
     * Kind is "command" (free script) or "preset".
     */
    "kind": string;
    "command": string;
    "preset": string;
    "params": { [_ in string]?: string } | null;

    /**
     * Snippet is the name of the saved snippet the command came from (display only).
     */
    "snippet": string;
    "sudo": boolean;
    "timeoutSec": number;
    "concurrency": number;
    "stopOnFailure": boolean;
}

/**
 * Summary counts servers by outcome.
 */
export interface Summary {
    "total": number;
    "queued": number;

    /**
     * connecting or running
     */
    "running": number;
    "ok": number;
    "failed": number;
    "timeout": number;
    "cancelled": number;
    "skipped": number;
}

/**
 * Target is a saved server with its readiness for the command center.
 */
export interface Target {
    "id": string;
    "name": string;
    "group": string;
    "host": string;
    "user": string;
    "port": number;
    "color": string;
    "environment": string;
    "tags": string[] | null;
    "role": string;

    /**
     * Readiness: connected | auto | needSecret | unavailable.
     */
    "readiness": string;

    /**
     * Via explains how it connects: ui | background | password | key | keyPassphrase | agent.
     */
    "via": string;

    /**
     * Reason is an error code when Readiness is unavailable.
     */
    "reason": string;

    /**
     * CanExec is false when the role forbids running commands.
     */
    "canExec": boolean;

    /**
     * Sudo: root | stored | unknown (sudo password not stored; works only with NOPASSWD).
     */
    "sudo": string;
}
