// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Alert is the state of one (rule, server, target) combination.
 */
export interface Alert {
    "key": string;
    "rule": string;
    "ruleName": string;
    "metric": string;
    "op": string;
    "threshold": number;
    "server": string;
    "serverName": string;
    "target": string;

    /**
     * pending | firing | resolved
     */
    "state": string;
    "severity": string;
    "value": number;

    /**
     * unix ms: condition first true
     */
    "since": number;
    "fired": number;
    "resolved": number;
    "acked": number;
    "ackedBy": string;
    "lastNotified": number;
}

/**
 * AlertCount is pushed to the UI for the sidebar badge.
 */
export interface AlertCount {
    "firing": number;
    "unacked": number;
    "critical": number;
}

/**
 * Channel is a notification destination. Secret material (bot tokens,
 * webhook URLs, SMTP passwords, routing keys) lives in the OS keychain.
 */
export interface Channel {
    "id": string;
    "name": string;

    /**
     * telegram | slack | discord | webhook | email | pagerduty | desktop
     */
    "type": string;
    "enabled": boolean;

    /**
     * Non-secret settings: chatId (telegram); url (webhook); host, port,
     * username, from, to, tls = starttls|tls|none (email).
     */
    "config": { [_ in string]?: string } | null;
    "hasSecret": boolean;

    /**
     * Default channels receive every rule's notifications.
     */
    "default": boolean;
}

/**
 * Check is one line of a server's health report.
 */
export interface Check {
    "id": string;

    /**
     * cpu | memory | disk | inode | load | swap | network | ssh | service | failed-units | container | http | ssl | backup
     */
    "kind": string;

    /**
     * target (mount, unit, URL…), "" for server-wide checks
     */
    "name": string;

    /**
     * ok | warn | crit | unknown
     */
    "status": string;
    "value": number;

    /**
     * raw detail (error text, status code…)
     */
    "detail": string;
}

export interface Container {
    "name": string;
    "state": string;
    "status": string;
    "health": string;
}

export interface DiskIO {
    "device": string;
    "readBps": number;
    "writeBps": number;
    "readIops": number;
    "writeIops": number;
    "latencyMs": number;
    "util": number;
}

/**
 * FleetItem summarises one server for the fleet view.
 */
export interface FleetItem {
    "server": string;
    "monitored": boolean;
    "collecting": boolean;
    "reachable": boolean;

    /**
     * health: ok | warn | crit | unknown | "" (no data)
     */
    "status": string;
    "ok": number;
    "total": number;
    "cpu": number;
    "mem": number;
    "disk": number;
    "load": number;
    "cpus": number;
    "uptime": number;
    "alerts": number;
    "lastSeen": number;
    "error": string;
}

/**
 * HTTPResult is the latest outcome of an HTTP health check.
 */
export interface HTTPResult {
    "name": string;
    "url": string;
    "ok": boolean;
    "status": number;
    "ms": number;
    "error": string;

    /**
     * days until the TLS certificate expires (-1 = n/a)
     */
    "certDays": number;
    "at": number;
}

/**
 * Health answers "is this server really OK right now?".
 */
export interface Health {
    "server": string;
    "ts": number;

    /**
     * ok | warn | crit | unknown
     */
    "status": string;
    "ok": number;
    "total": number;
    "checks": Check[] | null;
    "reachable": boolean;
    "error": string;
}

export interface Mount {
    "fs": string;
    "mount": string;
    "total": number;
    "used": number;
    "avail": number;
    "pct": number;
    "inodesTotal": number;
    "inodesUsed": number;
    "inodePct": number;
}

export interface NetIO {
    "iface": string;
    "rxBps": number;
    "txBps": number;
    "rxPps": number;
    "txPps": number;

    /**
     * per second, rx+tx
     */
    "errors": number;
    "drops": number;
    "rxTotal": number;
    "txTotal": number;
}

export interface Proc {
    "pid": number;
    "user": string;
    "cpu": number;
    "mem": number;
    "rss": number;
    "command": string;
}

/**
 * Rule is an alert rule. It applies to every monitored server matching its
 * scope (empty scope lists = all).
 */
export interface Rule {
    "id": string;
    "name": string;
    "enabled": boolean;

    /**
     * see metricInfo
     */
    "metric": string;

    /**
     * ">" | "<"
     */
    "op": string;
    "threshold": number;

    /**
     * ForSec: the condition must hold this long before the alert fires.
     */
    "forSec": number;

    /**
     * warn | crit
     */
    "severity": string;
    "servers": string[] | null;
    "environments": string[] | null;
    "tags": string[] | null;
    "groups": string[] | null;
    "channels": string[] | null;

    /**
     * RepeatMin re-notifies while firing and unacknowledged (0 = never).
     */
    "repeatMin": number;
    "notifyResolved": boolean;
    "builtin": boolean;
}

/**
 * SampleEvent carries the latest state of one server.
 */
export interface SampleEvent {
    "server": string;
    "snapshot": Snapshot | null;
    "health": Health;
    "http": HTTPResult[] | null;
    "reachable": boolean;
    "error": string;

    /**
     * unix ms of the attempt
     */
    "at": number;
}

/**
 * Series is a columnar time series: TS[i] with Values[field][i].
 */
export interface Series {
    "res": number;
    "ts": number[] | null;
    "values": { [_ in string]?: number[] | null } | null;
}

/**
 * Snapshot is the full, current picture of a server.
 */
export interface Snapshot {
    "server": string;

    /**
     * unix seconds (server clock)
     */
    "ts": number;
    "uptime": number;
    "cpus": number;

    /**
     * % busy
     */
    "cpu": number;
    "user": number;
    "system": number;
    "iowait": number;
    "steal": number;
    "cores": number[] | null;
    "load": number[];
    "procs": number;
    "running": number;
    "memTotal": number;
    "memUsed": number;
    "memAvail": number;
    "memCache": number;
    "memBuffer": number;
    "memPct": number;
    "swapTotal": number;
    "swapUsed": number;
    "swapPct": number;
    "mounts": Mount[] | null;
    "disks": DiskIO[] | null;
    "nets": NetIO[] | null;

    /**
     * Totals across devices/interfaces.
     */
    "diskRead": number;
    "diskWrite": number;
    "iops": number;
    "diskLat": number;
    "netRx": number;
    "netTx": number;
    "netErrors": number;
    "netDrops": number;
    "topCpu": Proc[] | null;
    "topMem": Proc[] | null;
    "failed": string[] | null;
    "units": UnitState[] | null;
    "containers": Container[] | null;
    "hasDocker": boolean;

    /**
     * Rates are only meaningful once two samples exist.
     */
    "hasRates": boolean;
}

export interface UnitState {
    "name": string;
    "state": string;
}
