// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Ack(key: string): $CancellablePromise<void> {
    return $Call.ByID(2444638760, key);
}

export function ActiveAlerts(): $CancellablePromise<$models.Alert[] | null> {
    return $Call.ByID(2479799898);
}

export function AlertCount(): $CancellablePromise<$models.AlertCount> {
    return $Call.ByID(1803083098);
}

export function AlertHistory(serverID: string, limit: number): $CancellablePromise<$models.Alert[] | null> {
    return $Call.ByID(893621205, serverID, limit);
}

export function Channels(): $CancellablePromise<$models.Channel[] | null> {
    return $Call.ByID(1295835567);
}

/**
 * CheckNow triggers an immediate collection (and HTTP checks).
 */
export function CheckNow(serverID: string): $CancellablePromise<void> {
    return $Call.ByID(442462587, serverID);
}

export function DeleteChannel(id: string): $CancellablePromise<void> {
    return $Call.ByID(2864769335, id);
}

export function DeleteRule(id: string): $CancellablePromise<void> {
    return $Call.ByID(2973391130, id);
}

export function Fleet(): $CancellablePromise<$models.FleetItem[] | null> {
    return $Call.ByID(1086121113);
}

/**
 * History returns stored metrics between from and to (unix seconds).
 */
export function History(serverID: string, $from: number, to: number): $CancellablePromise<$models.Series> {
    return $Call.ByID(31235337, serverID, $from, to);
}

/**
 * Latest returns the most recent sample of a server.
 */
export function Latest(serverID: string): $CancellablePromise<[$models.SampleEvent, boolean]> {
    return $Call.ByID(50692388, serverID);
}

/**
 * Live asks for 3-second sampling for the next 20 seconds (call it
 * periodically while a realtime view is open).
 */
export function Live(serverID: string): $CancellablePromise<void> {
    return $Call.ByID(4145445117, serverID);
}

/**
 * Metrics lists the metrics a rule can use with their unit.
 */
export function Metrics(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(1585154424);
}

/**
 * RestoreDefaultRules re-adds any missing built-in rule.
 */
export function RestoreDefaultRules(): $CancellablePromise<void> {
    return $Call.ByID(4280418367);
}

export function Rules(): $CancellablePromise<$models.Rule[] | null> {
    return $Call.ByID(1144414062);
}

export function SaveChannel(ch: $models.Channel, secret: string, setSecret: boolean): $CancellablePromise<$models.Channel> {
    return $Call.ByID(3954660933, ch, secret, setSecret);
}

export function SaveRule(r: $models.Rule): $CancellablePromise<$models.Rule> {
    return $Call.ByID(3667449636, r);
}

/**
 * SetMonitor turns background monitoring on/off for a server.
 */
export function SetMonitor(serverID: string, on: boolean): $CancellablePromise<void> {
    return $Call.ByID(3999349441, serverID, on);
}

/**
 * TestChannel sends a test message. For an unsaved or edited channel pass
 * the secret; "" uses the stored one.
 */
export function TestChannel(ch: $models.Channel, secret: string): $CancellablePromise<void> {
    return $Call.ByID(3872117930, ch, secret);
}
