// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ApplyResult is returned by every change to a site configuration.
 */
export interface ApplyResult {
    "id": string;
    "file": string;
    "testOutput": string;
    "reloaded": boolean;

    /**
     * engine stopped: validated only
     */
    "notRunning": boolean;
    "pendingCert": boolean;
    "warnings": string[] | null;
}

/**
 * AuthUser is a basic-auth account. Password is write-only: it is hashed
 * with bcrypt when the site is applied and never stored or returned.
 */
export interface AuthUser {
    "user": string;
    "password"?: string;
}

/**
 * CertInspect describes a pasted certificate + key (validated locally).
 */
export interface CertInspect {
    "subject": string;
    "issuer": string;
    "domains": string[] | null;
    "notBefore": number;
    "notAfter": number;
    "daysLeft": number;
    "status": string;
    "chainLen": number;
    "selfSigned": boolean;
    "keyType": string;

    /**
     * SHA-256 of the leaf
     */
    "fingerprint": string;

    /**
     * noIntermediate | notYetValid | expired | selfSigned
     */
    "warnings": string[] | null;
}

/**
 * CertOverview is the SSL tab content.
 */
export interface CertOverview {
    "certificates": Certificate[] | null;
    "renewal": RenewalStatus;
    "certbot": boolean;
    "certbotVersion": string;
    "pkgManager": string;
}

/**
 * Certificate is a TLS certificate found on the server. The monitoring
 * module uses Certificates() for expiry alerts.
 */
export interface Certificate {
    "name": string;
    "domains": string[] | null;

    /**
     * unix seconds (0 = unknown)
     */
    "notAfter": number;
    "notBefore": number;

    /**
     * certbot | nginx | caddy | custom
     */
    "source": string;
    "path": string;
    "keyPath": string;
    "issuer": string;
    "subject": string;
    "serial": string;
    "keyType": string;
    "daysLeft": number;

    /**
     * ok | warn | err | expired | unknown
     */
    "status": string;
    "staging": boolean;

    /**
     * site files referencing it
     */
    "usedBy": string[] | null;

    /**
     * file missing / unreadable
     */
    "error": string;
}

/**
 * EngineInfo is what detection found about one web server.
 */
export interface EngineInfo {
    /**
     * nginx | caddy | apache | traefik
     */
    "name": string;
    "installed": boolean;
    "running": boolean;

    /**
     * systemd unit enabled
     */
    "enabled": boolean;
    "version": string;
    "binary": string;
    "service": string;

    /**
     * Editable: the app can create/edit sites for it (nginx, caddy).
     */
    "editable": boolean;

    /**
     * nginx: debian | confd; caddy: caddyfile
     */
    "layout": string;

    /**
     * main config file
     */
    "config": string;

    /**
     * Result of nginx -t / caddy validate ("" = not run).
     */
    "testOk": boolean;
    "testRun": boolean;
    "testOutput": string;

    /**
     * traefik: runs as a container
     */
    "docker": boolean;

    /**
     * Caddy: whether /etc/caddy/Caddyfile imports sites/*.caddy.
     */
    "importsSites": boolean;
}

/**
 * GenContext holds the server facts the generator needs; the form loads
 * it once so previews are computed locally without a round trip.
 */
export interface GenContext {
    "engine": string;
    "http2Directive": boolean;
    "ipv6": boolean;
    "confDir": string;
    "htpasswdDir": string;
    "logDir": string;
    "basicAuthDirective": string;
    "layout": string;
    "version": string;

    /**
     * existing Let's Encrypt lineages
     */
    "leCerts": string[] | null;
    "customCerts": string[] | null;

    /**
     * last Let's Encrypt e-mail used
     */
    "email": string;
    "certbot": boolean;
}

/**
 * Header is one custom request (proxy_set_header / header_up) or response
 * (add_header / header) header.
 */
export interface Header {
    "name": string;
    "value": string;
}

/**
 * HistoryEntry is a previous version of a site file (kept for undo).
 */
export interface HistoryEntry {
    /**
     * unix ms
     */
    "ts": number;
    "action": string;
    "actor": string;
    "content": string;
}

/**
 * Listen is one listen directive of an nginx server block.
 */
export interface Listen {
    "addr": string;
    "port": number;
    "ssl": boolean;
    "http2": boolean;
    "defaultServer": boolean;
}

/**
 * LiveCert is what a TLS handshake with domain:443 returned.
 */
export interface LiveCert {
    "domain": string;

    /**
     * handshake done and chain valid for the name
     */
    "ok": boolean;

    /**
     * connection/handshake error
     */
    "error": string;

    /**
     * chain/name verification error
     */
    "verifyError": string;
    "issuer": string;
    "subject": string;
    "names": string[] | null;
    "notAfter": number;
    "daysLeft": number;
    "status": string;
}

/**
 * Preview is the generated configuration for a spec.
 */
export interface Preview {
    "file": string;
    "content": string;

    /**
     * Extra files written alongside (rate-limit zone, websocket map…).
     */
    "extras": PreviewFile[] | null;
    "pendingCert": boolean;
}

export interface PreviewFile {
    "path": string;
    "content": string;
}

/**
 * RenewTimer is a systemd timer that renews certificates.
 */
export interface RenewTimer {
    "unit": string;
    "active": boolean;

    /**
     * unix seconds (0 = unknown)
     */
    "next": number;
    "nextText": string;
    "last": number;
}

/**
 * RenewalStatus tells whether certificates renew automatically.
 */
export interface RenewalStatus {
    "timers": RenewTimer[] | null;
    "cron": string[] | null;
    "automatic": boolean;
}

/**
 * ServerBlock summarizes one server { } (nginx) or site block (caddy).
 */
export interface ServerBlock {
    "line": number;
    "serverNames": string[] | null;
    "listens": Listen[] | null;
    "root": string;
    "proxyPass": string[] | null;
    "return": string;
    "sslCert": string;
    "sslKey": string;

    /**
     * caddy: tls directive arguments
     */
    "tls": string;
}

/**
 * Site is a configuration file holding one or more virtual hosts.
 */
export interface Site {
    /**
     * absolute file path
     */
    "id": string;
    "engine": string;
    "file": string;

    /**
     * display name (primary domain / file name)
     */
    "name": string;
    "managed": boolean;
    "enabled": boolean;

    /**
     * lives in sites-available / conf.d / caddy sites dir
     */
    "canToggle": boolean;
    "domains": string[] | null;

    /**
     * proxy | static | redirect | other
     */
    "kind": string;

    /**
     * upstream / root / redirect URL
     */
    "target": string;
    "https": boolean;
    "http2": boolean;
    "default": boolean;

    /**
     * certificate file paths referenced
     */
    "certs": string[] | null;
    "blocks": ServerBlock[] | null;

    /**
     * managed sites only
     */
    "spec": SiteSpec | null;

    /**
     * PendingCert: managed with Let's Encrypt but the certificate isn't
     * issued yet (served over plain HTTP until then).
     */
    "pendingCert": boolean;
}

/**
 * SiteSpec is the form model of an app-managed site. It is stored (without
 * passwords) in the generated file's "# sm-meta:" line so editing round-trips.
 */
export interface SiteSpec {
    /**
     * nginx | caddy
     */
    "engine": string;

    /**
     * first = primary; the rest are aliases
     */
    "domains": string[] | null;

    /**
     * proxy | static | redirect
     */
    "type": string;

    /**
     * Reverse proxy
     * http://127.0.0.1:3000, https://h:8443, unix:/run/app.sock
     */
    "upstreams": string[] | null;

    /**
     * "" (round robin) | least_conn | ip_hash
     */
    "lbMethod": string;
    "webSocket": boolean;

    /**
     * Timeouts in seconds (0 = engine default).
     */
    "connectTimeout": number;
    "readTimeout": number;
    "sendTimeout": number;
    "requestHeaders": Header[] | null;

    /**
     * Static site
     */
    "root": string;
    "index": string;
    "spa": boolean;

    /**
     * Redirect
     */
    "redirectTo": string;

    /**
     * 301 | 302 | 307 | 308
     */
    "redirectCode": number;
    "preservePath": boolean;

    /**
     * TLS
     * none | letsencrypt | custom | internal (caddy)
     */
    "ssl": string;

    /**
     * Let's Encrypt lineage / custom certificate name
     */
    "certName": string;

    /**
     * custom: fullchain path
     */
    "certPath": string;

    /**
     * custom: private key path
     */
    "keyPath": string;

    /**
     * Let's Encrypt account e-mail
     */
    "email": string;

    /**
     * ecdsa | rsa
     */
    "keyType": string;
    "staging": boolean;
    "forceHttps": boolean;
    "http2": boolean;
    "hsts": boolean;
    "hstsMaxAge": number;
    "hstsSubdomains": boolean;

    /**
     * Misc
     */
    "responseHeaders": Header[] | null;

    /**
     * 0 = default
     */
    "maxBodyMb": number;
    "gzip": boolean;
    "rateLimit": boolean;
    "rateRps": number;
    "rateBurst": number;
    "rateNoDelay": boolean;
    "basicAuth": boolean;
    "authRealm": string;
    "authUsers": AuthUser[] | null;

    /**
     * "" = default path, "off" = disabled
     */
    "accessLog": string;
    "errorLog": string;

    /**
     * raw directives added to the main server block
     */
    "extra": string;
}

/**
 * SitesResult is the Domains tab content.
 */
export interface SitesResult {
    "sites": Site[] | null;

    /**
     * debian | confd | ""
     */
    "nginxLayout": string;
    "nginxTestOk": boolean;
    "nginxTest": string;

    /**
     * per-engine read problems (codes)
     */
    "errors": string[] | null;
}

/**
 * WebStatus is the detection result shown at the top of the panel.
 */
export interface WebStatus {
    "engines": EngineInfo[] | null;
    "certbot": boolean;
    "certbotVersion": string;

    /**
     * apt | dnf | yum | apk | ""
     */
    "pkgManager": string;
    "systemd": boolean;

    /**
     * processes listening on :80/:443
     */
    "listeners": string[] | null;
    "webroot": string;
}
