// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Apply creates (id = "") or updates a managed site, validates it with
 * nginx -t / caddy validate (rolling back on failure) and reloads.
 */
export function Apply(connID: string, id: string, spec: $models.SiteSpec, sudoPassword: string): $CancellablePromise<$models.ApplyResult> {
    return $Call.ByID(3648803921, connID, id, spec, sudoPassword);
}

/**
 * CertOverview is the SSL tab: certificates plus auto-renewal status.
 */
export function CertOverview(connID: string, sudoPassword: string): $CancellablePromise<$models.CertOverview> {
    return $Call.ByID(756590826, connID, sudoPassword);
}

/**
 * Certificates lists every certificate found on the server (certbot
 * lineages, files referenced by nginx/caddy sites, custom certificates).
 * It works without an open UI connection (used by monitoring).
 */
export function Certificates(connID: string, sudoPassword: string): $CancellablePromise<$models.Certificate[] | null> {
    return $Call.ByID(818228583, connID, sudoPassword);
}

/**
 * DeleteCertificate removes a certbot lineage (refused while a site uses it).
 */
export function DeleteCertificate(connID: string, name: string, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(2911357059, connID, name, sudoPassword);
}

/**
 * DeleteCustomCertificate removes /etc/ssl/server-manager/<name>.
 */
export function DeleteCustomCertificate(connID: string, name: string, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(1508790998, connID, name, sudoPassword);
}

/**
 * DeleteSite removes a site file (and its link and helper files).
 */
export function DeleteSite(connID: string, engine: string, file: string, sudoPassword: string): $CancellablePromise<$models.ApplyResult> {
    return $Call.ByID(1264142087, connID, engine, file, sudoPassword);
}

/**
 * FormContext gathers what the site form needs for an engine.
 */
export function FormContext(connID: string, engine: string, sudoPassword: string): $CancellablePromise<$models.GenContext> {
    return $Call.ByID(3356673532, connID, engine, sudoPassword);
}

/**
 * History lists the previous versions of a site file, newest first.
 */
export function History(connID: string, file: string): $CancellablePromise<$models.HistoryEntry[] | null> {
    return $Call.ByID(1930345473, connID, file);
}

/**
 * InspectCertificate validates a pasted PEM chain and key locally (nothing
 * is sent to the server) and describes the certificate.
 */
export function InspectCertificate(chainPEM: string, keyPEM: string): $CancellablePromise<$models.CertInspect> {
    return $Call.ByID(3076536788, chainPEM, keyPEM);
}

/**
 * InstallCertbot installs certbot with the distro package manager (job).
 */
export function InstallCertbot(connID: string, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(4228686509, connID, sudoPassword);
}

/**
 * InstallCertificate writes a validated certificate to
 * /etc/ssl/server-manager/<name>/{fullchain,privkey}.pem (root, 0600 in a
 * 0700 directory). replace allows overwriting an existing one (renewal);
 * nginx/caddy are then reloaded so they pick it up.
 */
export function InstallCertificate(connID: string, name: string, chainPEM: string, keyPEM: string, replace: boolean, sudoPassword: string): $CancellablePromise<$models.CertInspect> {
    return $Call.ByID(4217961617, connID, name, chainPEM, keyPEM, replace, sudoPassword);
}

/**
 * IssueCertificate obtains a Let's Encrypt certificate for a managed nginx
 * site (HTTP-01 through the shared webroot, so nginx keeps running), then
 * regenerates the site with TLS enabled and reloads. Runs as a job.
 */
export function IssueCertificate(connID: string, file: string, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(4185349385, connID, file, sudoPassword);
}

/**
 * LiveCheck connects to each domain on port 443 with SNI (8 s timeout, at
 * most 8 at a time) and reports the certificate actually served.
 */
export function LiveCheck(domains: string[] | null): $CancellablePromise<$models.LiveCert[] | null> {
    return $Call.ByID(3028756327, domains);
}

/**
 * Preview renders the configuration for a spec (pure; no server access).
 * id is the file of the site being edited ("" for a new site).
 */
export function Preview(gc: $models.GenContext, id: string, spec: $models.SiteSpec): $CancellablePromise<$models.Preview> {
    return $Call.ByID(537115689, gc, id, spec);
}

/**
 * ReadSite returns the raw content of a site's configuration file.
 */
export function ReadSite(connID: string, engine: string, file: string, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(2912933896, connID, engine, file, sudoPassword);
}

/**
 * RenewCertificate runs `certbot renew --cert-name X` as a job.
 */
export function RenewCertificate(connID: string, name: string, force: boolean, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(1995981463, connID, name, force, sudoPassword);
}

/**
 * RestoreVersion puts a previous version of a site file back (validated
 * and reloaded like any change; the current version joins the history).
 */
export function RestoreVersion(connID: string, engine: string, file: string, ts: number, sudoPassword: string): $CancellablePromise<$models.ApplyResult> {
    return $Call.ByID(3300747497, connID, engine, file, ts, sudoPassword);
}

/**
 * RevokeCertificate revokes a lineage at Let's Encrypt and deletes it.
 */
export function RevokeCertificate(connID: string, name: string, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(2168575376, connID, name, sudoPassword);
}

/**
 * SaveRaw replaces a configuration file with edited text (validated like
 * any change). Only files the engine loads or disabled site files qualify.
 */
export function SaveRaw(connID: string, engine: string, file: string, content: string, sudoPassword: string): $CancellablePromise<$models.ApplyResult> {
    return $Call.ByID(263268980, connID, engine, file, content, sudoPassword);
}

/**
 * SetEnabled enables or disables a site: a sites-enabled link (Debian
 * layout) or a ".disabled" suffix (conf.d, caddy sites/).
 */
export function SetEnabled(connID: string, engine: string, file: string, enabled: boolean, sudoPassword: string): $CancellablePromise<$models.ApplyResult> {
    return $Call.ByID(771768574, connID, engine, file, enabled, sudoPassword);
}

/**
 * Sites lists the virtual hosts of nginx and caddy.
 */
export function Sites(connID: string, sudoPassword: string): $CancellablePromise<$models.SitesResult> {
    return $Call.ByID(2856256325, connID, sudoPassword);
}

/**
 * Status detects the web servers, certbot and the package manager, and
 * validates the nginx/caddy configurations.
 */
export function Status(connID: string, sudoPassword: string): $CancellablePromise<$models.WebStatus> {
    return $Call.ByID(2267036105, connID, sudoPassword);
}

/**
 * TestRenewal runs `certbot renew --dry-run` (all certificates, or one).
 */
export function TestRenewal(connID: string, name: string, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(1305977353, connID, name, sudoPassword);
}
