// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Download saves the full output of a query (every matching line, up to
 * 500 MB) to a local file chosen in a save dialog. Returns path "" when the
 * user cancels.
 */
export function Download(connID: string, spec: $models.QuerySpec, sudoPassword: string, title: string): $CancellablePromise<$models.DownloadResult> {
    return $Call.ByID(2973486461, connID, spec, sudoPassword, title);
}

/**
 * Query returns the log lines matching spec (oldest first).
 */
export function Query(connID: string, spec: $models.QuerySpec, sudoPassword: string): $CancellablePromise<$models.QueryResult> {
    return $Call.ByID(349405383, connID, spec, sudoPassword);
}

/**
 * ServiceControl starts/stops/restarts/reloads/enables/disables a service
 * through systemctl, rc-service or service (as root via sudo).
 */
export function ServiceControl(connID: string, name: string, action: string, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(3625540421, connID, name, action, sudoPassword);
}

/**
 * ServiceDetail returns everything about a systemd service: state, resource
 * usage (CPU% measured over ~1 s), restart policy, dependencies, unit file
 * and its last 50 journal lines.
 */
export function ServiceDetail(connID: string, name: string): $CancellablePromise<$models.ServiceDetail> {
    return $Call.ByID(1213666049, connID, name);
}

/**
 * ServiceList lists services: systemd units merged with their unit-file
 * state, or OpenRC / SysV services when systemd isn't used.
 */
export function ServiceList(connID: string): $CancellablePromise<$models.ServiceList> {
    return $Call.ByID(1023085224, connID);
}

/**
 * ServiceStats samples CPU time and memory of every running service.
 */
export function ServiceStats(connID: string): $CancellablePromise<$models.UnitStats> {
    return $Call.ByID(3869305683, connID);
}

/**
 * SetAutoRestart installs (or removes) a drop-in making systemd restart the
 * service when it fails, then reloads systemd.
 */
export function SetAutoRestart(connID: string, name: string, enabled: boolean, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(4089667663, connID, name, enabled, sudoPassword);
}

/**
 * Sources discovers the logs available on the server. Files and containers
 * hidden from the login user are listed through sudo when it works without
 * prompting (NOPASSWD, cached or saved password); otherwise they're missing.
 */
export function Sources(connID: string): $CancellablePromise<$models.SourceList> {
    return $Call.ByID(622592973, connID);
}

/**
 * StartStream follows a log source live. Lines arrive as "logs:lines"
 * events carrying the returned stream id; the final event has done=true.
 * The time range is ignored; Lines is the initial backlog (max 1000).
 */
export function StartStream(connID: string, spec: $models.QuerySpec, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(2035343947, connID, spec, sudoPassword);
}

/**
 * StopAllStreams stops every stream of a server (e.g. when the panel closes).
 */
export function StopAllStreams(connID: string): $CancellablePromise<void> {
    return $Call.ByID(3423489681, connID);
}

/**
 * StopStream stops a live stream (no error if it already ended).
 */
export function StopStream(streamID: string): $CancellablePromise<void> {
    return $Call.ByID(521557961, streamID);
}
