// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apperr$0 from "../../internal/apperr/models.js";

/**
 * DownloadResult describes a saved log file ("" path = cancelled).
 */
export interface DownloadResult {
    "path": string;
    "bytes": number;
    "lines": number;
    "truncated": boolean;
}

/**
 * LinesEvent is one batch of a live stream. The last event of a stream has
 * Done set (and Error when it ended abnormally).
 */
export interface LinesEvent {
    "streamId": string;
    "lines": LogLine[] | null;

    /**
     * lines skipped because the UI could not keep up
     */
    "dropped": number;
    "done": boolean;
    "error": apperr$0.Error | null;
}

/**
 * LogLine is one structured log entry.
 */
export interface LogLine {
    /**
     * unix ms, 0 when unknown
     */
    "ts": number;

    /**
     * emerg|alert|crit|err|warning|notice|info|debug, "" when unknown
     */
    "level": string;

    /**
     * unit / syslog identifier / container / file
     */
    "source": string;

    /**
     * the text without timestamp/prefix
     */
    "message": string;

    /**
     * the full line as a human would read it
     */
    "raw": string;
}

/**
 * QueryResult is the outcome of Query, oldest line first.
 */
export interface QueryResult {
    "lines": LogLine[] | null;

    /**
     * LimitReached: as many lines as requested were returned; older ones may exist.
     */
    "limitReached": boolean;

    /**
     * Truncated: the output size cap was hit, some lines were dropped.
     */
    "truncated": boolean;

    /**
     * Partial: a time-filtered file query only scanned the end of a large file.
     */
    "partial": boolean;
    "sudo": boolean;
    "tookMs": number;
}

/**
 * QuerySpec selects log lines.
 */
export interface QuerySpec {
    /**
     * journal | unit | kernel | auth | file | docker
     */
    "kind": string;

    /**
     * unit name, file path or container name/id
     */
    "target": string;

    /**
     * tail N (1..10000); 0 = default (download: all)
     */
    "lines": number;

    /**
     * unix seconds, 0 = unbounded
     */
    "since": number;

    /**
     * unix seconds, 0 = unbounded
     */
    "until": number;

    /**
     * "" or emerg|alert|crit|err|warning|notice|info|debug (this level and more severe)
     */
    "level": string;
    "search": string;
    "regex": boolean;
    "caseSensitive": boolean;
}

/**
 * ServiceDetail describes one systemd service.
 */
export interface ServiceDetail {
    "name": string;
    "description": string;
    "loadState": string;
    "activeState": string;
    "subState": string;
    "unitFileState": string;
    "type": string;
    "user": string;
    "mainPid": number;

    /**
     * ActiveEnterTimestamp as printed by systemd
     */
    "since": string;

    /**
     * seconds since the main process started, -1 = not running
     */
    "uptime": number;

    /**
     * bytes, -1 = n/a
     */
    "memory": number;
    "cpuNSec": number;

    /**
     * over ~1 s, 100 = one core, -1 = n/a
     */
    "cpuPercent": number;
    "tasks": number;
    "nRestarts": number;

    /**
     * no | on-failure | always…
     */
    "restart": string;

    /**
     * "100ms", "5s"
     */
    "restartSec": string;
    "execStart": string;
    "fragmentPath": string;
    "dropInPaths": string[] | null;
    "requires": string[] | null;
    "wants": string[] | null;
    "after": string[] | null;
    "before": string[] | null;
    "wantedBy": string[] | null;
    "requiredBy": string[] | null;

    /**
     * UnitFile is `systemctl cat` (fragment + drop-ins), read-only.
     */
    "unitFile": string;

    /**
     * AutoRestart: the app's drop-in (Restart=on-failure) is installed.
     */
    "autoRestart": boolean;
    "autoRestartPath": string;
    "logs": LogLine[] | null;

    /**
     * LogsNeedSudo: the journal needs sudo and no password is available yet.
     */
    "logsNeedSudo": boolean;
    "logsError": string;
}

/**
 * ServiceList is the list of services and the init system managing them.
 */
export interface ServiceList {
    /**
     * systemd | openrc | sysv | none
     */
    "init": string;
    "units": Unit[] | null;
}

/**
 * Source is a log source the server offers.
 */
export interface Source {
    /**
     * journal | kernel | auth | unit | file | docker
     */
    "kind": string;

    /**
     * unit, path or container ("" for journal/kernel/auth)
     */
    "target": string;
    "label": string;
    "needsSudo": boolean;

    /**
     * well-known file (syslog, auth.log, nginx…)
     */
    "common": boolean;

    /**
     * rotated/compressed file (.1, .gz, -20240101)
     */
    "rotated": boolean;
    "size": number;

    /**
     * unix seconds
     */
    "mtime": number;

    /**
     * unit active state / container state
     */
    "state": string;
    "description": string;
}

/**
 * SourceList is what Sources discovered.
 */
export interface SourceList {
    "sources": Source[] | null;

    /**
     * journald available
     */
    "journal": boolean;
    "systemd": boolean;
    "docker": boolean;

    /**
     * JournalSudo: reading the system journal needs sudo.
     */
    "journalSudo": boolean;

    /**
     * DockerError explains why containers could not be listed.
     */
    "dockerError": string;
}

/**
 * Unit is a service as listed by the init system.
 */
export interface Unit {
    "name": string;

    /**
     * loaded | not-found | masked | "" (unit file only)
     */
    "load": string;

    /**
     * active | inactive | failed | activating…
     */
    "active": string;

    /**
     * running | exited | dead | failed…
     */
    "sub": string;
    "description": string;

    /**
     * enabled | disabled | static | masked | indirect | generated…
     */
    "unitFileState": string;
}

/**
 * UnitStat is a running service's resource usage (systemd cgroup accounting).
 */
export interface UnitStat {
    "name": string;
    "mainPid": number;

    /**
     * bytes, -1 = not available
     */
    "memory": number;

    /**
     * cumulative CPU time, -1 = not available
     */
    "cpuNSec": number;

    /**
     * -1 = not available
     */
    "tasks": number;
}

/**
 * UnitStats is one sample of every running service. CPU% is the CPUNSec
 * delta between two samples divided by the SampleNs delta.
 */
export interface UnitStats {
    /**
     * server uptime in ns when sampled
     */
    "sampleNs": number;
    "units": UnitStat[] | null;
}
