// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apperr$0 from "../apperr/models.js";

/**
 * AuditEntry is one record of the tamper-evident audit log. Each entry's
 * hash covers its content and the previous entry's hash, so editing or
 * deleting a past record breaks the chain (see VerifyAudit).
 */
export interface AuditEntry {
    "id": number;

    /**
     * unix ms
     */
    "ts": number;
    "actor": string;
    "server": string;
    "serverName": string;
    "action": string;
    "target": string;
    "detail": string;
    "ok": boolean;
    "error": string;
    "prevHash": string;
    "hash": string;
}

/**
 * AuditQuery filters the audit log.
 */
export interface AuditQuery {
    "server": string;

    /**
     * prefix match
     */
    "action": string;

    /**
     * matches actor/target/detail
     */
    "text": string;

    /**
     * unix ms
     */
    "since": number;
    "until": number;
    "limit": number;

    /**
     * id, for paging
     */
    "before": number;
}

/**
 * AuditVerification is the result of checking the hash chain.
 */
export interface AuditVerification {
    "ok": boolean;
    "checked": number;

    /**
     * id of the first bad entry
     */
    "brokenAt": number;
}

export interface ConnStatusEvent {
    "id": string;
    "status": string;
    "error": apperr$0.Error | null;
}

/**
 * Event is an entry on a server's timeline (alerts, connection changes,
 * service/container state changes, deployments, backups, user actions).
 * Code + Params are translated by the frontend ("ev.<code>").
 */
export interface Event {
    "id": number;

    /**
     * unix ms
     */
    "ts": number;
    "server": string;

    /**
     * alert | conn | service | container | deploy | backup | action | security | health
     */
    "kind": string;

    /**
     * info | ok | warn | crit
     */
    "severity": string;
    "code": string;
    "params": { [_ in string]?: string } | null;
    "detail": string;
    "actor": string;
}

/**
 * EventQuery filters the timeline.
 */
export interface EventQuery {
    "server": string;
    "kinds": string[] | null;
    "severity": string[] | null;
    "since": number;
    "until": number;
    "limit": number;
    "before": number;
}

/**
 * JobInfo describes a long-running operation (deploy, compose up, backup,
 * certificate issue, package install…) whose output streams to the UI.
 */
export interface JobInfo {
    "id": string;
    "server": string;
    "kind": string;
    "title": string;

    /**
     * unix ms
     */
    "started": number;

    /**
     * 0 while running
     */
    "finished": number;

    /**
     * running | done | error | cancelled
     */
    "state": string;
    "error": apperr$0.Error | null;

    /**
     * Log is the retained output (the tail, when very long).
     */
    "log": string;

    /**
     * Written counts every byte of output so far; a UI that fetched Log can
     * skip job:output events whose Offset+len(Data) <= Written.
     */
    "written": number;

    /**
     * Result is an optional value set by the job (e.g. a run id).
     */
    "result": string;
}

export interface JobOutputEvent {
    "id": string;

    /**
     * Offset is the number of bytes written before Data.
     */
    "offset": number;
    "data": string;
}

/**
 * Settings are app-wide preferences stored in the local database.
 */
export interface Settings {
    /**
     * OperatorName identifies the person using this app in the audit log
     * (e.g. an email). Empty = OS account.
     */
    "operatorName": string;

    /**
     * CollectInterval is the metrics sampling period in seconds.
     */
    "collectInterval": number;

    /**
     * BackgroundMode keeps the app running in the menu bar / tray when the
     * window is closed so monitoring, alerts and scheduled backups go on.
     */
    "backgroundMode": boolean;

    /**
     * TerminalIdleMinutes closes terminals idle this long (0 = never).
     */
    "terminalIdleMinutes": number;

    /**
     * RecordTerminal saves terminal sessions (asciicast) for later review.
     */
    "recordTerminal": boolean;

    /**
     * DesktopNotify shows OS notifications for alerts.
     */
    "desktopNotify": boolean;

    /**
     * ConfirmProduction requires typing the server name before dangerous
     * actions on production servers.
     */
    "confirmProduction": boolean;

    /**
     * Retention (days, 0 = forever).
     */
    "auditRetentionDays": number;
    "eventRetentionDays": number;

    /**
     * CommandConcurrency limits parallel servers in the command center.
     */
    "commandConcurrency": number;

    /**
     * NotifyLang is the language of alert notifications (vi | en).
     */
    "notifyLang": string;
}
