// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService exposes app-wide features: settings, audit log, event
 * timeline and background jobs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../internal/core/models.js";

/**
 * Allowed reports whether the server's role grants perm.
 */
export function Allowed(serverID: string, perm: string): $CancellablePromise<boolean> {
    return $Call.ByID(3792986965, serverID, perm);
}

export function Audit(q: core$0.AuditQuery): $CancellablePromise<core$0.AuditEntry[] | null> {
    return $Call.ByID(433663946, q);
}

export function CancelJob(id: string): $CancellablePromise<void> {
    return $Call.ByID(1434752220, id);
}

/**
 * DefaultActor is the identity used when no operator name is set.
 */
export function DefaultActor(): $CancellablePromise<string> {
    return $Call.ByID(763093197);
}

export function Events(q: core$0.EventQuery): $CancellablePromise<core$0.Event[] | null> {
    return $Call.ByID(3843646022, q);
}

/**
 * ExportAudit writes the (filtered) audit log to a CSV file chosen by the
 * user. Returns the path, or "" if cancelled.
 */
export function ExportAudit(q: core$0.AuditQuery, title: string): $CancellablePromise<string> {
    return $Call.ByID(2591967500, q, title);
}

export function GetSettings(): $CancellablePromise<core$0.Settings> {
    return $Call.ByID(959702832);
}

/**
 * Job returns a job including its output so far.
 */
export function Job(id: string): $CancellablePromise<[core$0.JobInfo, boolean]> {
    return $Call.ByID(2016391402, id);
}

export function Jobs(server: string): $CancellablePromise<core$0.JobInfo[] | null> {
    return $Call.ByID(3423797467, server);
}

/**
 * RolePerms lists what each server role may do.
 */
export function RolePerms(): $CancellablePromise<{ [_ in string]?: string[] | null } | null> {
    return $Call.ByID(2010289702);
}

export function SaveSettings($in: core$0.Settings): $CancellablePromise<core$0.Settings> {
    return $Call.ByID(2615800491, $in);
}

export function VerifyAudit(): $CancellablePromise<core$0.AuditVerification> {
    return $Call.ByID(4110491881);
}
