// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService exposes remote file-system operations over SFTP, with a few
 * operations (search, recursive delete, archives) done through standard
 * POSIX tools via exec for speed.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelTransfer(id: string): $CancellablePromise<void> {
    return $Call.ByID(4198195609, id);
}

export function Chmod(connID: string, p: string, mode: number, recursive: boolean): $CancellablePromise<void> {
    return $Call.ByID(986774649, connID, p, mode, recursive);
}

/**
 * Chown changes owner and/or group (empty = unchanged), through sudo when
 * the login user may not.
 */
export function Chown(connID: string, p: string, owner: string, group: string, recursive: boolean, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(1739287709, connID, p, owner, group, recursive, sudoPassword);
}

export function Compress(connID: string, dir: string, names: string[] | null, archiveName: string): $CancellablePromise<void> {
    return $Call.ByID(846814292, connID, dir, names, archiveName);
}

export function Copy(connID: string, paths: string[] | null, destDir: string): $CancellablePromise<void> {
    return $Call.ByID(497649685, connID, paths, destDir);
}

export function CreateDir(connID: string, p: string): $CancellablePromise<void> {
    return $Call.ByID(1003914611, connID, p);
}

export function CreateFile(connID: string, p: string): $CancellablePromise<$models.FileEntry> {
    return $Call.ByID(1928847690, connID, p);
}

export function Delete(connID: string, paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(705397891, connID, paths);
}

export function Download(connID: string, remotePath: string, localPath: string): $CancellablePromise<string> {
    return $Call.ByID(1945944136, connID, remotePath, localPath);
}

export function Extract(connID: string, archive: string): $CancellablePromise<void> {
    return $Call.ByID(3664106697, connID, archive);
}

export function Home(connID: string): $CancellablePromise<string> {
    return $Call.ByID(2654608447, connID);
}

export function ListDir(connID: string, dir: string): $CancellablePromise<$models.FileEntry[] | null> {
    return $Call.ByID(2334523159, connID, dir);
}

export function ListDirSudo(connID: string, dir: string, password: string): $CancellablePromise<$models.FileEntry[] | null> {
    return $Call.ByID(2875049222, connID, dir, password);
}

export function Move(connID: string, paths: string[] | null, destDir: string): $CancellablePromise<void> {
    return $Call.ByID(3144946469, connID, paths, destDir);
}

/**
 * PickAndDownload asks where to save and downloads a file or folder.
 */
export function PickAndDownload(connID: string, remotePath: string, isDir: boolean, title: string): $CancellablePromise<string> {
    return $Call.ByID(3766353450, connID, remotePath, isDir, title);
}

/**
 * PickAndUpload opens a native picker and uploads the chosen files (or a
 * folder when folders is true) into remoteDir. Returns the transfer id, or
 * "" if the user cancelled the dialog.
 */
export function PickAndUpload(connID: string, remoteDir: string, folders: boolean, title: string): $CancellablePromise<string> {
    return $Call.ByID(3350765743, connID, remoteDir, folders, title);
}

export function ReadFile(connID: string, p: string): $CancellablePromise<$models.FileContent> {
    return $Call.ByID(1592377338, connID, p);
}

export function ReadFileSudo(connID: string, p: string, password: string): $CancellablePromise<$models.FileContent> {
    return $Call.ByID(152700847, connID, p, password);
}

export function Rename(connID: string, $from: string, to: string): $CancellablePromise<void> {
    return $Call.ByID(2178653530, connID, $from, to);
}

/**
 * Search finds files by name, or by content when content is true, using
 * find/grep on the server. Results are capped at 500.
 */
export function Search(connID: string, root: string, query: string, content: boolean): $CancellablePromise<$models.SearchHit[] | null> {
    return $Call.ByID(875601604, connID, root, query, content);
}

export function Stat(connID: string, p: string): $CancellablePromise<$models.FileEntry> {
    return $Call.ByID(1742403242, connID, p);
}

export function SudoOp(connID: string, op: string, paths: string[] | null, dest: string, mode: number, recursive: boolean, password: string): $CancellablePromise<void> {
    return $Call.ByID(437458266, connID, op, paths, dest, mode, recursive, password);
}

export function Upload(connID: string, localPaths: string[] | null, remoteDir: string): $CancellablePromise<string> {
    return $Call.ByID(3796881225, connID, localPaths, remoteDir);
}

export function WriteFile(connID: string, p: string, content: string, expectedModTime: number, force: boolean): $CancellablePromise<$models.SaveResult> {
    return $Call.ByID(1018709945, connID, p, content, expectedModTime, force);
}

export function WriteFileSudo(connID: string, p: string, content: string, password: string, expectedModTime: number, force: boolean): $CancellablePromise<$models.SaveResult> {
    return $Call.ByID(2139787616, connID, p, content, password, expectedModTime, force);
}
