// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apperr$0 from "../internal/apperr/models.js";

/**
 * ConfigResult is the outcome of ApplyConfig.
 */
export interface ConfigResult {
    "ok": boolean;
    "output": string;
}

/**
 * ConnectResult tells the UI whether it needs to ask the user something
 * (a secret, or confirmation of an unknown host key) before retrying.
 */
export interface ConnectResult {
    /**
     * ok | need-secret | hostkey
     */
    "status": string;
    "home": string;
    "hostKey": HostKeyInfo | null;
}

export interface DiskInfo {
    "filesystem": string;
    "mount": string;
    "total": number;
    "used": number;
    "avail": number;
}

export interface FileContent {
    "path": string;
    "content": string;
    "size": number;
    "modTime": number;
    "binary": boolean;
    "tooLarge": boolean;
    "readOnly": boolean;
    "sudo": boolean;
}

export interface FileDropEvent {
    "files": string[] | null;
    "target": { [_ in string]?: string } | null;
}

export interface FileEntry {
    "name": string;
    "path": string;
    "isDir": boolean;
    "isLink": boolean;
    "linkTarget": string;
    "size": number;
    "mode": string;
    "perm": number;
    "modTime": number;
    "owner": string;
    "group": string;
}

export interface HostKeyInfo {
    "host": string;
    "port": number;
    "keyType": string;
    "fingerprint": string;
    "keyBase64": string;
    "mismatch": boolean;
}

export interface Process {
    "pid": number;
    "user": string;
    "cpu": number;
    "mem": number;
    "rss": number;
    "elapsed": string;
    "command": string;
}

/**
 * Recording describes a saved terminal session.
 */
export interface Recording {
    /**
     * "<serverId>/<name>.cast"
     */
    "file": string;
    "server": string;

    /**
     * unix ms
     */
    "started": number;
    "size": number;
}

export interface SaveResult {
    "conflict": boolean;
    "entry": FileEntry;
}

export interface SearchHit {
    "path": string;
    "line": number;
    "text": string;
}

export interface ServiceUnit {
    "name": string;
    "load": string;
    "active": string;
    "sub": string;
    "description": string;

    /**
     * UnitFileState comes from list-unit-files: enabled, disabled, static,
     * masked, indirect… ("" when unknown).
     */
    "unitFileState": string;
}

export interface SysInfo {
    "hostname": string;
    "os": string;
    "kernel": string;
    "uptime": number;
    "load": number[];
    "cpus": number;
    "cpuModel": string;
    "cpuUsage": number;
    "memTotal": number;
    "memUsed": number;
    "memAvail": number;
    "swapTotal": number;
    "swapUsed": number;
    "disks": DiskInfo[] | null;
    "netRx": number;
    "netTx": number;
    "users": number;
    "time": number;
}

export interface TermDataEvent {
    "id": string;

    /**
     * base64
     */
    "data": string;
}

export interface TermExitEvent {
    "id": string;
    "error": apperr$0.Error | null;
}

export interface TransferEvent {
    "id": string;
    "connId": string;

    /**
     * upload | download
     */
    "kind": string;
    "name": string;

    /**
     * number of additional top-level items
     */
    "more": number;
    "current": string;
    "done": number;
    "total": number;
    "files": number;
    "filesDone": number;

    /**
     * running | done | error | cancelled
     */
    "state": string;
    "error": apperr$0.Error | null;
    "target": string;
}
