// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ServerService manages saved profiles and connections.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../internal/store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Connect connects to a saved server. secret overrides the stored secret;
 * when saveSecret is true a provided secret is written to the keychain.
 */
export function Connect(id: string, secret: string, saveSecret: boolean): $CancellablePromise<$models.ConnectResult> {
    return $Call.ByID(3527564073, id, secret, saveSecret);
}

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(3207056666, id);
}

export function Disconnect(id: string): $CancellablePromise<void> {
    return $Call.ByID(4114582875, id);
}

export function IsConnected(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(312044688, id);
}

export function List(): $CancellablePromise<store$0.Server[] | null> {
    return $Call.ByID(2732599537);
}

/**
 * PickKeyFile opens a native file picker in ~/.ssh.
 */
export function PickKeyFile(title: string): $CancellablePromise<string> {
    return $Call.ByID(4120676521, title);
}

export function Reconnect(id: string): $CancellablePromise<void> {
    return $Call.ByID(3154858422, id);
}

export function Save(server: store$0.Server, secret: string, setSecret: boolean): $CancellablePromise<store$0.Server> {
    return $Call.ByID(3272632440, server, secret, setSecret);
}

/**
 * SetSudoPassword stores (or with "" forgets) the sudo password in the
 * keychain so background tasks can use it.
 */
export function SetSudoPassword(id: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(3205074647, id, password);
}

/**
 * Test tries a connection with unsaved settings and closes it immediately.
 */
export function Test(server: store$0.Server, secret: string): $CancellablePromise<$models.ConnectResult> {
    return $Call.ByID(2895436149, server, secret);
}

export function TrustHostKey(host: string, port: number, keyBase64: string): $CancellablePromise<void> {
    return $Call.ByID(3831886422, host, port, keyBase64);
}
