// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService reads server metrics and manages processes/services using
 * only tools that ship with the OS (/proc, df, ps, systemctl).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sshx$0 from "../internal/sshx/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyConfig validates and reloads a service after its config was edited:
 * kind = nginx | caddy | apache | sshd | systemd | service (unit = name).
 * The reload only happens when validation passes.
 */
export function ApplyConfig(connID: string, kind: string, unit: string, sudoPassword: string): $CancellablePromise<$models.ConfigResult> {
    return $Call.ByID(114178311, connID, kind, unit, sudoPassword);
}

export function Exec(connID: string, command: string, useSudo: boolean, sudoPassword: string): $CancellablePromise<sshx$0.ExecResult> {
    return $Call.ByID(2885970358, connID, command, useSudo, sudoPassword);
}

export function Info(connID: string): $CancellablePromise<$models.SysInfo> {
    return $Call.ByID(3934610951, connID);
}

export function Kill(connID: string, pid: number, signal: string, useSudo: boolean, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(2312552371, connID, pid, signal, useSudo, sudoPassword);
}

export function Processes(connID: string): $CancellablePromise<$models.Process[] | null> {
    return $Call.ByID(2689462060, connID);
}

export function ServiceAction(connID: string, name: string, action: string, useSudo: boolean, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(3720369660, connID, name, action, useSudo, sudoPassword);
}

/**
 * ServiceLogs returns the last lines of a unit's journal.
 */
export function ServiceLogs(connID: string, name: string, lines: number, useSudo: boolean, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(2187496157, connID, name, lines, useSudo, sudoPassword);
}

/**
 * Services lists systemd services (loaded units merged with the unit-file
 * state). The Logs module's LogsService.ServiceList also covers OpenRC/SysV.
 */
export function Services(connID: string): $CancellablePromise<$models.ServiceUnit[] | null> {
    return $Call.ByID(227282591, connID);
}
