// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalService runs interactive shells over SSH PTYs. Output is streamed
 * to the frontend as base64 chunks so multi-byte characters split across
 * reads survive intact (xterm.js decodes the byte stream itself).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(id: string): $CancellablePromise<void> {
    return $Call.ByID(339264758, id);
}

export function DeleteRecording(file: string): $CancellablePromise<void> {
    return $Call.ByID(263913020, file);
}

export function Open(connID: string, cwd: string, cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByID(3954331090, connID, cwd, cols, rows);
}

/**
 * OpenExec opens an interactive console (see execCommand) in a terminal.
 */
export function OpenExec(connID: string, kind: string, target: string, cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByID(1422368175, connID, kind, target, cols, rows);
}

/**
 * ReadRecording returns an asciicast file's content (max 50 MB).
 */
export function ReadRecording(file: string): $CancellablePromise<string> {
    return $Call.ByID(2852773953, file);
}

/**
 * RecordingOf returns the recording file of an open terminal ("" if none).
 */
export function RecordingOf(id: string): $CancellablePromise<string> {
    return $Call.ByID(4040071948, id);
}

/**
 * Recordings lists saved terminal sessions (all servers when serverID is "").
 */
export function Recordings(serverID: string): $CancellablePromise<$models.Recording[] | null> {
    return $Call.ByID(3113693086, serverID);
}

export function Resize(id: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(443729646, id, cols, rows);
}

export function Write(id: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(311916309, id, data);
}
