// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum AuthType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthPassword = "password",
    AuthKey = "key",
    AuthAgent = "agent",
};

/**
 * HTTPCheck is an HTTP(S) health check attached to a server.
 */
export interface HTTPCheck {
    "name": string;
    "url": string;

    /**
     * Expect is the expected status code (0 = any 2xx/3xx).
     */
    "expect": number;

    /**
     * Contains, when set, must appear in the response body.
     */
    "contains": string;

    /**
     * ViaServer runs the request on the server itself (curl/wget), for
     * endpoints only reachable from localhost.
     */
    "viaServer": boolean;
}

/**
 * Server is a saved connection profile.
 */
export interface Server {
    "id": string;
    "name": string;
    "group": string;
    "host": string;
    "port": number;
    "user": string;
    "authType": AuthType;
    "keyPath": string;
    "defaultPath": string;
    "color": string;

    /**
     * HasSecret reports whether a password/passphrase is stored in the keychain.
     */
    "hasSecret": boolean;
    "createdAt": number;
    "updatedAt": number;
    "lastUsed": number;

    /**
     * Organisation.
     * production | staging | development | ""
     */
    "environment": string;
    "tags": string[] | null;
    "region": string;
    "provider": string;
    "notes": string;

    /**
     * Role limits what this app may do on the server (admin, operator,
     * developer, viewer); see core.Require. Empty means admin.
     */
    "role": string;

    /**
     * Monitoring: when Monitor is set the app keeps its own connection to
     * collect metrics, evaluate health checks and alerts in the background.
     */
    "monitor": boolean;
    "watchServices": string[] | null;
    "httpChecks": HTTPCheck[] | null;

    /**
     * OSInfo is detected on connect ("Ubuntu 24.04 LTS").
     */
    "osInfo": string;

    /**
     * SudoSaved reports whether a sudo password is stored in the keychain.
     */
    "sudoSaved": boolean;
}
