// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as core$0 from "../../../../../server-manager/internal/core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as services$0 from "../../../../../server-manager/services/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as backup$0 from "../../../../../server-manager/services/backup/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as command$0 from "../../../../../server-manager/services/command/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as deploy$0 from "../../../../../server-manager/services/deploy/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as logs$0 from "../../../../../server-manager/services/logs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as monitor$0 from "../../../../../server-manager/services/monitor/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "backup:run": backup$0.RunEvent;
            "command:finished": command$0.FinishedEvent;
            "command:update": command$0.ServerResult;
            "conn:status": core$0.ConnStatusEvent;
            "deploy:step": deploy$0.StepEvent;
            "files:dropped": services$0.FileDropEvent;
            "job:done": core$0.JobInfo;
            "job:output": core$0.JobOutputEvent;
            "logs:lines": logs$0.LinesEvent;
            "monitor:alerts": monitor$0.AlertCount;
            "monitor:sample": monitor$0.SampleEvent;
            "term:data": services$0.TermDataEvent;
            "term:exit": services$0.TermExitEvent;
            "timeline:new": core$0.Event;
            "transfer:progress": services$0.TransferEvent;
        }
    }
}
