// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ComposeAction runs up | pull | restart | stop | start | down on a project
 * as a job and returns the job id.
 */
export function ComposeAction(connID: string, name: string, action: string, opts: $models.ComposeActionOptions, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(1738102983, connID, name, action, opts, sudoPassword);
}

/**
 * ComposeHistory lists stored versions of a compose file (newest first,
 * without content).
 */
export function ComposeHistory(connID: string, filePath: string): $CancellablePromise<$models.ComposeVersion[] | null> {
    return $Call.ByID(1545269959, connID, filePath);
}

/**
 * ComposeProjectDetail returns a project's containers (`compose ps -a`) and
 * the services its files declare.
 */
export function ComposeProjectDetail(connID: string, name: string, sudoPassword: string): $CancellablePromise<$models.ComposeDetail> {
    return $Call.ByID(1287704583, connID, name, sudoPassword);
}

/**
 * ComposeProjects lists Compose projects.
 */
export function ComposeProjects(connID: string, sudoPassword: string): $CancellablePromise<$models.ComposeProject[] | null> {
    return $Call.ByID(526884911, connID, sudoPassword);
}

/**
 * ComposeVersionContent returns a stored version's content.
 */
export function ComposeVersionContent(connID: string, filePath: string, id: string): $CancellablePromise<string> {
    return $Call.ByID(2844081304, connID, filePath, id);
}

/**
 * ContainerAction runs start | stop | restart | pause | unpause | kill.
 */
export function ContainerAction(connID: string, name: string, action: string, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(2171082180, connID, name, action, sudoPassword);
}

/**
 * ContainerInspect returns formatted details and the raw inspect JSON.
 */
export function ContainerInspect(connID: string, name: string, sudoPassword: string): $CancellablePromise<$models.ContainerDetail> {
    return $Call.ByID(3545563506, connID, name, sudoPassword);
}

/**
 * ContainerLogs returns the last lines of a container's output (stdout and
 * stderr merged). since: "15m", "2h", a unix time or a date; "" = all.
 */
export function ContainerLogs(connID: string, name: string, tail: number, since: string, timestamps: boolean, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(2194300181, connID, name, tail, since, timestamps, sudoPassword);
}

/**
 * Containers lists every container.
 */
export function Containers(connID: string, sudoPassword: string): $CancellablePromise<$models.Container[] | null> {
    return $Call.ByID(20453287, connID, sudoPassword);
}

/**
 * DeployCompose validates and atomically writes a compose file (keeping the
 * previous content in the history), then runs `up -d --remove-orphans`, as
 * a job. Validation errors abort before anything is written.
 */
export function DeployCompose(connID: string, req: $models.DeployRequest, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(1320616756, connID, req, sudoPassword);
}

/**
 * DiskUsage summarizes `docker system df`.
 */
export function DiskUsage(connID: string, sudoPassword: string): $CancellablePromise<$models.DiskUsage[] | null> {
    return $Call.ByID(2689645125, connID, sudoPassword);
}

/**
 * Images lists images with the containers that use them.
 */
export function Images(connID: string, sudoPassword: string): $CancellablePromise<$models.Image[] | null> {
    return $Call.ByID(3935186193, connID, sudoPassword);
}

/**
 * Networks lists networks with their subnets and attached (running) containers.
 */
export function Networks(connID: string, sudoPassword: string): $CancellablePromise<$models.Network[] | null> {
    return $Call.ByID(1560947624, connID, sudoPassword);
}

/**
 * PruneImages removes dangling images (all: every image without a container).
 */
export function PruneImages(connID: string, all: boolean, sudoPassword: string): $CancellablePromise<$models.PruneResult> {
    return $Call.ByID(963726823, connID, all, sudoPassword);
}

/**
 * PruneVolumes removes unused anonymous volumes (all: named ones too).
 */
export function PruneVolumes(connID: string, all: boolean, sudoPassword: string): $CancellablePromise<$models.PruneResult> {
    return $Call.ByID(1136650864, connID, all, sudoPassword);
}

/**
 * PullImage pulls an image as a job.
 */
export function PullImage(connID: string, ref: string, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(1456273769, connID, ref, sudoPassword);
}

/**
 * ReadComposeFile returns a compose file's content (Exists=false when absent).
 */
export function ReadComposeFile(connID: string, filePath: string, sudoPassword: string): $CancellablePromise<$models.ComposeFile> {
    return $Call.ByID(3350652207, connID, filePath, sudoPassword);
}

/**
 * RecreateContainer recreates a Compose-managed container from its project
 * files (`up -d --force-recreate --no-deps <service>`) as a job.
 */
export function RecreateContainer(connID: string, name: string, pull: boolean, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(4249281509, connID, name, pull, sudoPassword);
}

/**
 * RemoveContainer runs docker rm (force: also running ones; volumes: remove
 * its anonymous volumes).
 */
export function RemoveContainer(connID: string, name: string, force: boolean, volumes: boolean, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(3469965258, connID, name, force, volumes, sudoPassword);
}

/**
 * RemoveImage removes an image (or one of its tags). An image used by
 * containers is refused with docker.imageInUse unless force is set.
 */
export function RemoveImage(connID: string, ref: string, force: boolean, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(1640523348, connID, ref, force, sudoPassword);
}

/**
 * RemoveNetwork deletes a user-defined network.
 */
export function RemoveNetwork(connID: string, name: string, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(1002436871, connID, name, sudoPassword);
}

/**
 * RemoveVolume deletes a volume (docker refuses volumes in use).
 */
export function RemoveVolume(connID: string, name: string, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(3292092137, connID, name, sudoPassword);
}

/**
 * Stats samples resource usage of running containers (takes ~2 s).
 */
export function Stats(connID: string, sudoPassword: string): $CancellablePromise<$models.ContainerStats[] | null> {
    return $Call.ByID(510630142, connID, sudoPassword);
}

/**
 * Status detects Docker on the server (always fresh). A missing docker or a
 * stopped daemon is not an error; sudo errors are (so the UI can prompt).
 */
export function Status(connID: string, sudoPassword: string): $CancellablePromise<$models.Status> {
    return $Call.ByID(1723014389, connID, sudoPassword);
}

/**
 * ValidateCompose checks candidate content for spec.Path: it is written to a
 * temporary file in the same directory (so relative paths and env files
 * resolve), checked with `compose config -q`, and removed.
 */
export function ValidateCompose(connID: string, spec: $models.ComposeSpec, content: string, sudoPassword: string): $CancellablePromise<$models.ValidateResult> {
    return $Call.ByID(634130347, connID, spec, content, sudoPassword);
}

/**
 * VolumeSizes returns volume sizes in bytes from `docker system df -v`
 * (can take a while on large hosts).
 */
export function VolumeSizes(connID: string, sudoPassword: string): $CancellablePromise<{ [_ in string]?: number } | null> {
    return $Call.ByID(3121713893, connID, sudoPassword);
}

/**
 * Volumes lists volumes with the containers that mount them.
 */
export function Volumes(connID: string, sudoPassword: string): $CancellablePromise<$models.Volume[] | null> {
    return $Call.ByID(3732014666, connID, sudoPassword);
}
