// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ComposeActionOptions tunes ComposeAction.
 */
export interface ComposeActionOptions {
    /**
     * up: pull images first (--pull always)
     */
    "pull": boolean;

    /**
     * down: also remove named volumes (-v)
     */
    "removeVolumes": boolean;
}

/**
 * ComposeContainer is one row of `docker compose ps -a`.
 */
export interface ComposeContainer {
    "name": string;
    "service": string;
    "image": string;
    "state": string;
    "status": string;
    "health": string;
    "exitCode": number;
    "ports": string;
    "created": number;
}

/**
 * ComposeDetail is a project with its containers and declared services.
 */
export interface ComposeDetail {
    "project": ComposeProject;
    "containers": ComposeContainer[] | null;

    /**
     * Defined lists the services declared in the config files.
     */
    "defined": string[] | null;
    "configError": string;
}

/**
 * ComposeFile is a compose file's content and metadata.
 */
export interface ComposeFile {
    "path": string;
    "exists": boolean;
    "content": string;

    /**
     * sha256 of Content ("" when missing)
     */
    "sha": string;
    "mode": string;
    "owner": string;

    /**
     * Writable: the login user can replace it without sudo.
     */
    "writable": boolean;
}

/**
 * ComposeProject is a Compose project found on the server (from
 * `docker compose ls -a` and/or container labels).
 */
export interface ComposeProject {
    "name": string;

    /**
     * "running(2), exited(1)"
     */
    "status": string;
    "configFiles": string[] | null;
    "envFiles": string[] | null;
    "workingDir": string;
    "running": number;
    "total": number;
    "unhealthy": number;

    /**
     * services with containers
     */
    "services": string[] | null;
}

/**
 * ComposeSpec identifies a compose file within its project.
 */
export interface ComposeSpec {
    "project": string;

    /**
     * "" = directory of Path
     */
    "workingDir": string;

    /**
     * all config files, in order ("" = [Path])
     */
    "files": string[] | null;
    "envFiles": string[] | null;

    /**
     * the file being edited (one of Files)
     */
    "path": string;
}

/**
 * ComposeVersion is a stored previous content of a compose file.
 */
export interface ComposeVersion {
    "id": string;

    /**
     * unix ms (when it was replaced)
     */
    "ts": number;
    "actor": string;
    "sha": string;
    "size": number;

    /**
     * save | rollback: what replaced it
     */
    "note": string;
    "content"?: string;
}

/**
 * Container is one row of `docker ps -a`, with its Compose labels.
 */
export interface Container {
    "id": string;
    "name": string;
    "image": string;
    "command": string;

    /**
     * unix s
     */
    "created": number;

    /**
     * running | exited | paused | restarting | created | dead | removing
     */
    "state": string;

    /**
     * "Up 3 minutes (healthy)"
     */
    "status": string;

    /**
     * healthy | unhealthy | starting | ""
     */
    "health": string;
    "ports": string;
    "networks": string[] | null;

    /**
     * com.docker.compose.project
     */
    "project": string;

    /**
     * com.docker.compose.service
     */
    "service": string;
    "workingDir": string;
    "configFiles": string[] | null;
    "envFiles": string[] | null;
}

export interface ContainerDetail {
    "id": string;
    "name": string;
    "image": string;
    "imageId": string;
    "created": number;
    "state": string;
    "health": string;
    "failingStreak": number;
    "startedAt": number;
    "finishedAt": number;
    "exitCode": number;
    "oomKilled": boolean;
    "error": string;
    "pid": number;
    "restartCount": number;

    /**
     * "unless-stopped", "on-failure:5"
     */
    "restartPolicy": string;
    "entrypoint": string[] | null;
    "cmd": string[] | null;
    "workingDir": string;
    "user": string;
    "hostname": string;
    "privileged": boolean;
    "networkMode": string;
    "memoryLimit": number;

    /**
     * cores
     */
    "cpuLimit": number;
    "healthCheck": string[] | null;
    "env": EnvVar[] | null;
    "mounts": Mount[] | null;
    "networks": NetAttach[] | null;
    "ports": PortMap[] | null;
    "labels": Label[] | null;
    "healthLog": HealthEntry[] | null;
    "project": string;
    "service": string;

    /**
     * Raw is the full `docker inspect` JSON, indented.
     */
    "raw": string;
}

/**
 * ContainerStats is one sample of `docker stats` (running containers only).
 */
export interface ContainerStats {
    "id": string;
    "name": string;

    /**
     * % of one core (can exceed 100)
     */
    "cpu": number;
    "memUsage": number;
    "memLimit": number;
    "memPct": number;
    "netRx": number;
    "netTx": number;
    "blockRead": number;
    "blockWrite": number;
    "pids": number;
}

/**
 * DeployRequest saves a compose file and deploys the project.
 */
export interface DeployRequest {
    "spec": ComposeSpec;
    "content": string;

    /**
     * ExpectedSha is the sha of the content the editor started from; the
     * save is refused (docker.fileChanged) if the file changed meanwhile.
     * "" skips the check.
     */
    "expectedSha": string;
    "pull": boolean;

    /**
     * Kind: "save" (edit), "rollback" (restore a stored version) or "new"
     * (create a project; refused when the file exists).
     */
    "kind": string;

    /**
     * rollback: the restored version
     */
    "versionId": string;
}

export interface DiskUsage {
    /**
     * Images | Containers | Local Volumes | Build Cache
     */
    "type": string;
    "total": number;
    "active": number;
    "size": number;
    "reclaimable": number;
}

export interface EnvVar {
    "key": string;
    "value": string;

    /**
     * key looks like a secret; the UI masks it
     */
    "secret": boolean;
}

export interface HealthEntry {
    "start": number;
    "end": number;
    "exitCode": number;
    "output": string;
}

export interface Image {
    /**
     * sha256:…
     */
    "id": string;
    "repository": string;
    "tag": string;
    "digest": string;
    "created": number;
    "size": number;
    "dangling": boolean;

    /**
     * container names
     */
    "usedBy": string[] | null;
}

export interface Label {
    "key": string;
    "value": string;
}

export interface Mount {
    /**
     * volume | bind | tmpfs
     */
    "type": string;
    "name": string;
    "source": string;
    "destination": string;
    "mode": string;
    "rw": boolean;
}

export interface NetAttach {
    "network": string;
    "ip": string;
    "ipv6": string;
    "gateway": string;
    "mac": string;
    "aliases": string[] | null;
}

export interface NetContainer {
    "name": string;
    "ipv4": string;
}

export interface Network {
    "id": string;
    "name": string;
    "driver": string;
    "scope": string;
    "internal": boolean;
    "created": number;
    "subnets": string[] | null;
    "gateways": string[] | null;
    "containers": NetContainer[] | null;
    "project": string;

    /**
     * bridge / host / none: can't be removed
     */
    "builtin": boolean;
}

export interface PortMap {
    /**
     * "80/tcp"
     */
    "container": string;
    "hostIp": string;

    /**
     * "" = exposed only
     */
    "hostPort": string;
}

export interface PruneResult {
    /**
     * bytes
     */
    "reclaimed": number;
    "output": string;
}

/**
 * Status describes the Docker installation on a server.
 */
export interface Status {
    "installed": boolean;
    "clientVersion": string;
    "serverVersion": string;
    "daemonRunning": boolean;
    "daemonError": string;

    /**
     * the login user can't reach the daemon socket
     */
    "needSudo": boolean;

    /**
     * "plugin" (docker compose) | "legacy" (docker-compose) | ""
     */
    "compose": string;

    /**
     * e.g. "2.33.0"
     */
    "composeVersion": string;
}

/**
 * ValidateResult is the outcome of `compose config -q` on a candidate.
 */
export interface ValidateResult {
    "ok": boolean;

    /**
     * errors, or warnings when OK
     */
    "output": string;
}

export interface Volume {
    "name": string;
    "driver": string;
    "mountpoint": string;
    "scope": string;
    "created": number;

    /**
     * com.docker.compose.project
     */
    "project": string;

    /**
     * 64-hex name
     */
    "anonymous": boolean;
    "usedBy": string[] | null;

    /**
     * -1 = unknown (see VolumeSizes)
     */
    "size": number;
}
