// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Error {
    "code": string;
    "params"?: { [_ in string]?: string } | null;

    /**
     * Detail carries the underlying technical message (e.g. command stderr),
     * shown verbatim after the translated text.
     */
    "detail"?: string;
}
