package web

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"path"
	"regexp"
	"strconv"
	"strings"
)

const (
	managedMarker = "# managed-by: server-manager"
	metaPrefix    = "# sm-meta: "
	acmeWebroot   = "/var/www/letsencrypt"
	wsMapVar      = "$sm_connection_upgrade"
	wsMapFile     = "sm-websocket-map.conf"
)

// metaWrap is what the "# sm-meta:" line holds.
type metaWrap struct {
	V    int      `json:"v"`
	Spec SiteSpec `json:"spec"`
}

// encodeMeta serializes the spec (without passwords) for the meta line.
// json.Marshal escapes control characters, so the line cannot be broken.
func encodeMeta(sp SiteSpec) string {
	cp := sp
	cp.AuthUsers = make([]AuthUser, len(sp.AuthUsers))
	for i, u := range sp.AuthUsers {
		cp.AuthUsers[i] = AuthUser{User: u.User}
	}
	b, _ := json.Marshal(metaWrap{V: 1, Spec: cp})
	return string(b)
}

// parseMeta reads the managed marker and spec from a file's header lines.
func parseMeta(content string) (bool, *SiteSpec) {
	lines := strings.SplitN(content, "\n", 8)
	if len(lines) == 0 || strings.TrimSpace(lines[0]) != managedMarker {
		return false, nil
	}
	for _, l := range lines[1:] {
		l = strings.TrimSpace(l)
		if strings.HasPrefix(l, metaPrefix) {
			var w metaWrap
			if err := json.Unmarshal([]byte(strings.TrimPrefix(l, metaPrefix)), &w); err != nil || w.V != 1 {
				return true, nil
			}
			sp := w.Spec
			return true, &sp
		}
	}
	return true, nil
}

// ngxQ quotes a value as an nginx double-quoted string. Validation already
// rejected control characters; escaping '\' and '"' keeps the value inside
// a single token so it can never add directives.
func ngxQ(s string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(s) + `"`
}

var identSafe = regexp.MustCompile(`[^a-z0-9_]`)

// ngxIdent makes an identifier (upstream/zone name) from a site name. The
// hash suffix keeps it unique ("a-b.com" and "a.b.com" differ).
func ngxIdent(prefix, name string) string {
	sum := sha256.Sum256([]byte(name))
	return prefix + identSafe.ReplaceAllString(strings.ToLower(name), "_") + "_" + hex.EncodeToString(sum[:3])
}

// ngxGenOpts carries server facts the generator needs.
type ngxGenOpts struct {
	Name           string // site name (file stem)
	HasCert        bool   // the certificate files exist (Let's Encrypt)
	HTTP2Directive bool   // nginx >= 1.25.1: "http2 on;" instead of "listen … http2"
	IPv6           bool
	ConfDir        string // http-level conf dir for zone/map files ("" = inline)
	Htpasswd       string // basic-auth user file path
	LogDir         string // default log directory
}

type genOutput struct {
	Content     string
	Extras      []PreviewFile // http-context files to write
	PendingCert bool
}

func letsEncryptPaths(certName string) (string, string) {
	return "/etc/letsencrypt/live/" + certName + "/fullchain.pem", "/etc/letsencrypt/live/" + certName + "/privkey.pem"
}

// rateLimitFile / wsMapPath are the http-context helper files.
func rateLimitFile(confDir, name string) string {
	return path.Join(confDir, "sm-ratelimit-"+name+".conf")
}

// genNginx renders a normalized spec.
func genNginx(sp SiteSpec, o ngxGenOpts) genOutput {
	var out genOutput
	var b strings.Builder
	w := func(indent int, format string, args ...any) {
		b.WriteString(strings.Repeat("\t", indent))
		fmt.Fprintf(&b, format, args...)
		b.WriteByte('\n')
	}
	b.WriteString(managedMarker + "\n")
	b.WriteString(metaPrefix + encodeMeta(sp) + "\n")
	b.WriteString("# Generated by Server Manager. Edit this site in the app: manual changes are replaced when it is saved again.\n\n")

	tls := sp.SSL == SSLLetsEncrypt || sp.SSL == SSLCustom
	certPath, keyPath := sp.CertPath, sp.KeyPath
	if sp.SSL == SSLLetsEncrypt {
		certPath, keyPath = letsEncryptPaths(sp.CertName)
		if !o.HasCert {
			tls = false
			out.PendingCert = true
		}
	}
	names := strings.Join(sp.Domains, " ")
	upName := ngxIdent("sm_up_", o.Name)
	zone := ngxIdent("sm_rl_", o.Name)

	// Rate-limit zone (http context).
	if sp.RateLimit {
		zoneLine := fmt.Sprintf("limit_req_zone $binary_remote_addr zone=%s:10m rate=%dr/s;", zone, sp.RateRPS)
		if o.ConfDir != "" {
			out.Extras = append(out.Extras, PreviewFile{
				Path:    rateLimitFile(o.ConfDir, o.Name),
				Content: managedMarker + "\n# Rate limit zone for " + sp.Domains[0] + "\n" + zoneLine + "\n",
			})
		} else {
			w(0, "%s", zoneLine)
			b.WriteByte('\n')
		}
	}
	wsConn := wsMapVar
	if sp.WebSocket {
		if o.ConfDir != "" {
			out.Extras = append(out.Extras, PreviewFile{Path: path.Join(o.ConfDir, wsMapFile), Content: wsMapContent()})
		} else {
			wsConn = `"upgrade"`
		}
	}

	// Upstream group.
	ups := make([]Upstream, 0, len(sp.Upstreams))
	for _, raw := range sp.Upstreams {
		u, _ := parseUpstream(raw)
		ups = append(ups, u)
	}
	group := sp.Type == TypeProxy && (len(ups) > 1 || sp.LBMethod != "")
	if group {
		w(0, "upstream %s {", upName)
		if sp.LBMethod != "" {
			w(1, "%s;", sp.LBMethod)
		}
		for _, u := range ups {
			if u.Scheme == "unix" {
				w(1, "server %s;", ngxQ("unix:"+u.Socket))
			} else {
				w(1, "server %s;", u.HostPort())
			}
		}
		w(1, "keepalive 16;")
		w(0, "}")
		b.WriteByte('\n')
	}

	body := func(indent int) {
		if sp.AccessLog == "off" {
			w(indent, "access_log off;")
		} else {
			p := sp.AccessLog
			if p == "" {
				p = path.Join(o.LogDir, o.Name+".access.log")
			}
			w(indent, "access_log %s;", ngxQ(p))
		}
		if sp.ErrorLog != "off" {
			p := sp.ErrorLog
			if p == "" {
				p = path.Join(o.LogDir, o.Name+".error.log")
			}
			w(indent, "error_log %s;", ngxQ(p))
		}
		if sp.MaxBodyMB > 0 {
			w(indent, "client_max_body_size %dm;", sp.MaxBodyMB)
		}
		if sp.Gzip {
			w(indent, "gzip on;")
			w(indent, "gzip_vary on;")
			w(indent, "gzip_proxied any;")
			w(indent, "gzip_comp_level 5;")
			w(indent, "gzip_min_length 256;")
			w(indent, "gzip_types text/plain text/css text/xml text/javascript application/javascript application/json application/xml application/rss+xml application/wasm image/svg+xml;")
		}
		if sp.BasicAuth {
			w(indent, "auth_basic %s;", ngxQ(sp.AuthRealm))
			w(indent, "auth_basic_user_file %s;", ngxQ(o.Htpasswd))
		}
		if sp.RateLimit {
			line := fmt.Sprintf("limit_req zone=%s", zone)
			if sp.RateBurst > 0 {
				line += fmt.Sprintf(" burst=%d", sp.RateBurst)
			}
			if sp.RateNoDelay {
				line += " nodelay"
			}
			w(indent, "%s;", line)
			w(indent, "limit_req_status 429;")
		}
		for _, h := range sp.ResponseHeaders {
			w(indent, "add_header %s %s always;", h.Name, ngxQ(h.Value))
		}
		if sp.Extra != "" {
			b.WriteByte('\n')
			w(indent, "# Extra directives")
			for _, l := range strings.Split(sp.Extra, "\n") {
				if strings.TrimSpace(l) == "" {
					b.WriteByte('\n')
					continue
				}
				w(indent, "%s", strings.TrimRight(l, " \t"))
			}
		}
		b.WriteByte('\n')
		switch sp.Type {
		case TypeProxy:
			target := ""
			if group {
				scheme := "http"
				if ups[0].Scheme == "https" {
					scheme = "https"
				}
				target = scheme + "://" + upName
			} else if u := ups[0]; u.Scheme == "unix" {
				target = "http://unix:" + u.Socket + ":"
			} else {
				target = u.Scheme + "://" + u.HostPort() + u.Path
			}
			w(indent, "location / {")
			w(indent+1, "proxy_pass %s;", ngxQ(target))
			w(indent+1, "proxy_http_version 1.1;")
			custom := map[string]bool{}
			for _, h := range sp.RequestHeaders {
				custom[strings.ToLower(h.Name)] = true
			}
			defaults := [][2]string{
				{"Host", "$host"},
				{"X-Real-IP", "$remote_addr"},
				{"X-Forwarded-For", "$proxy_add_x_forwarded_for"},
				{"X-Forwarded-Proto", "$scheme"},
				{"X-Forwarded-Host", "$host"},
			}
			if sp.WebSocket {
				defaults = append(defaults, [2]string{"Upgrade", "$http_upgrade"}, [2]string{"Connection", wsConn})
			} else if group {
				defaults = append(defaults, [2]string{"Connection", `""`})
			}
			for _, d := range defaults {
				if !custom[strings.ToLower(d[0])] {
					w(indent+1, "proxy_set_header %s %s;", d[0], d[1])
				}
			}
			for _, h := range sp.RequestHeaders {
				w(indent+1, "proxy_set_header %s %s;", h.Name, ngxQ(h.Value))
			}
			if ups[0].Scheme == "https" {
				w(indent+1, "proxy_ssl_server_name on;")
			}
			if sp.ConnectTimeout > 0 {
				w(indent+1, "proxy_connect_timeout %ds;", sp.ConnectTimeout)
			}
			read, send := sp.ReadTimeout, sp.SendTimeout
			if sp.WebSocket {
				if read == 0 {
					read = 3600
				}
				if send == 0 {
					send = 3600
				}
			}
			if read > 0 {
				w(indent+1, "proxy_read_timeout %ds;", read)
			}
			if send > 0 {
				w(indent+1, "proxy_send_timeout %ds;", send)
			}
			w(indent, "}")
		case TypeStatic:
			w(indent, "root %s;", ngxQ(sp.Root))
			w(indent, "index %s;", sp.Index)
			w(indent, "location / {")
			if sp.SPA {
				w(indent+1, "try_files $uri $uri/ /index.html;")
			} else {
				w(indent+1, "try_files $uri $uri/ =404;")
			}
			w(indent, "}")
		case TypeRedirect:
			target := sp.RedirectTo
			if sp.PreservePath {
				target = strings.TrimRight(target, "/") + "$request_uri"
			}
			w(indent, "location / {")
			w(indent+1, "return %d %s;", sp.RedirectCode, ngxQ(target))
			w(indent, "}")
		}
	}

	listen := func(port int, ssl bool) {
		suffix := ""
		if ssl {
			suffix = " ssl"
			if sp.HTTP2 && !o.HTTP2Directive {
				suffix += " http2"
			}
		}
		w(1, "listen %d%s;", port, suffix)
		if o.IPv6 {
			w(1, "listen [::]:%d%s;", port, suffix)
		}
	}

	// Port 80
	w(0, "server {")
	listen(80, false)
	w(1, "server_name %s;", names)
	b.WriteByte('\n')
	w(1, "# Let's Encrypt HTTP-01 challenges (issuance and renewal without stopping nginx)")
	w(1, "location ^~ /.well-known/acme-challenge/ {")
	w(2, "root %s;", acmeWebroot)
	w(2, "default_type \"text/plain\";")
	if sp.BasicAuth {
		w(2, "auth_basic off;")
	}
	w(2, "try_files $uri =404;")
	w(1, "}")
	b.WriteByte('\n')
	if tls && sp.ForceHTTPS {
		w(1, "location / {")
		w(2, "return 301 https://$host$request_uri;")
		w(1, "}")
	} else {
		body(1)
	}
	w(0, "}")

	if tls {
		b.WriteByte('\n')
		w(0, "server {")
		listen(443, true)
		if sp.HTTP2 && o.HTTP2Directive {
			w(1, "http2 on;")
		}
		w(1, "server_name %s;", names)
		b.WriteByte('\n')
		w(1, "ssl_certificate %s;", ngxQ(certPath))
		w(1, "ssl_certificate_key %s;", ngxQ(keyPath))
		w(1, "ssl_protocols TLSv1.2 TLSv1.3;")
		w(1, "ssl_session_timeout 1d;")
		if sp.HSTS {
			v := "max-age=" + strconv.Itoa(sp.HSTSMaxAge)
			if sp.HSTSSubdomains {
				v += "; includeSubDomains"
			}
			w(1, "add_header Strict-Transport-Security %s always;", ngxQ(v))
		}
		b.WriteByte('\n')
		body(1)
		w(0, "}")
	}
	out.Content = b.String()
	return out
}

func wsMapContent() string {
	return managedMarker + "\n# WebSocket upgrade map shared by the sites managed by Server Manager.\n" +
		"map $http_upgrade " + wsMapVar + " {\n\tdefault upgrade;\n\t''      close;\n}\n"
}

// nginxVersionAtLeast compares "1.25.3" style versions.
func versionAtLeast(v string, want ...int) bool {
	parts := strings.Split(strings.TrimSpace(v), ".")
	for i, w := range want {
		if i >= len(parts) {
			return false
		}
		n, err := strconv.Atoi(strings.TrimFunc(parts[i], func(r rune) bool { return r < '0' || r > '9' }))
		if err != nil {
			return false
		}
		if n != w {
			return n > w
		}
	}
	return true
}
