// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Activity lists sessions (pg_stat_activity / processlist) and lock waits.
 */
export function Activity(connID: string, targetID: string, sudoPassword: string): $CancellablePromise<$models.Activity> {
    return $Call.ByID(1391588392, connID, targetID, sudoPassword);
}

/**
 * CancelSession cancels the running query of a session (pg_cancel_backend,
 * KILL QUERY) or, with terminate, closes the session (pg_terminate_backend,
 * KILL CONNECTION).
 */
export function CancelSession(connID: string, targetID: string, id: number, terminate: boolean, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(790551969, connID, targetID, id, terminate, sudoPassword);
}

/**
 * ClearHistory forgets the query history of a target.
 */
export function ClearHistory(connID: string, targetID: string): $CancellablePromise<void> {
    return $Call.ByID(461963462, connID, targetID);
}

/**
 * CreateDatabase creates a database (owner: optional Postgres role).
 */
export function CreateDatabase(connID: string, targetID: string, name: string, owner: string, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(1380477540, connID, targetID, name, owner, sudoPassword);
}

/**
 * CreateUser creates a login role (Postgres) or user@host (MySQL, host
 * defaults to localhost) with a password, optionally granting all
 * privileges on a database. The password is sent on stdin only; Postgres
 * receives a SCRAM verifier computed locally.
 */
export function CreateUser(connID: string, targetID: string, name: string, password: string, host: string, grantDatabase: string, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(2649935414, connID, targetID, name, password, host, grantDatabase, sudoPassword);
}

/**
 * Databases lists the databases of a Postgres or MySQL target with sizes.
 */
export function Databases(connID: string, targetID: string, sudoPassword: string): $CancellablePromise<$models.DatabaseInfo[] | null> {
    return $Call.ByID(999470085, connID, targetID, sudoPassword);
}

/**
 * DeleteSnippet removes a saved query.
 */
export function DeleteSnippet(id: string): $CancellablePromise<void> {
    return $Call.ByID(2523919383, id);
}

/**
 * DeleteTarget removes a saved target (a detected one reverts to its
 * detected settings) and its stored password.
 */
export function DeleteTarget(connID: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(3450268495, connID, id);
}

/**
 * Detect scans the server for database engines (client binaries, server
 * binaries, systemd units, listening ports, processes) and for running
 * Docker containers of postgres/mysql/mariadb/redis images. When Docker
 * needs root, sudo is used if it works without prompting (NOPASSWD, or a
 * known password); otherwise Docker is reported as "denied".
 */
export function Detect(connID: string, sudoPassword: string): $CancellablePromise<$models.Detection> {
    return $Call.ByID(2376121118, connID, sudoPassword);
}

/**
 * DetectSudo is Detect that reports sudo errors (sudo.required,
 * sudo.wrongPassword) when Docker needs root, so the UI can ask for the
 * password and scan the containers.
 */
export function DetectSudo(connID: string, sudoPassword: string): $CancellablePromise<$models.Detection> {
    return $Call.ByID(888307051, connID, sudoPassword);
}

/**
 * EnableStatStatements runs CREATE EXTENSION pg_stat_statements in a
 * database (the library must already be in shared_preload_libraries).
 */
export function EnableStatStatements(connID: string, targetID: string, database: string, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(2371089922, connID, targetID, database, sudoPassword);
}

/**
 * History returns the last query runs of a target (newest first).
 */
export function History(connID: string, targetID: string): $CancellablePromise<$models.HistoryEntry[] | null> {
    return $Call.ByID(141362507, connID, targetID);
}

/**
 * Overview returns the status summary of a target.
 */
export function Overview(connID: string, targetID: string, sudoPassword: string): $CancellablePromise<$models.Overview> {
    return $Call.ByID(340017374, connID, targetID, sudoPassword);
}

/**
 * Ping checks that the target is reachable with its settings; returns the
 * server version.
 */
export function Ping(connID: string, targetID: string, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(1623950637, connID, targetID, sudoPassword);
}

/**
 * RedisCommand runs one command in the Redis console. Commands that change
 * data or server state need allowWrite (the UI asks for confirmation);
 * KEYS on a database with more than 10000 keys needs it too.
 */
export function RedisCommand(connID: string, targetID: string, db: number, command: string, allowWrite: boolean, sudoPassword: string): $CancellablePromise<$models.RedisResult> {
    return $Call.ByID(3354637513, connID, targetID, db, command, allowWrite, sudoPassword);
}

/**
 * ResetSlowStats clears pg_stat_statements / performance_schema digests.
 */
export function ResetSlowStats(connID: string, targetID: string, database: string, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(3021133488, connID, targetID, database, sudoPassword);
}

/**
 * RunQuery runs SQL on a Postgres or MySQL target. Read-only by default:
 * only reading statements are accepted and they run in a read-only
 * transaction with default_transaction_read_only / SET SESSION TRANSACTION
 * READ ONLY. Every run is audited and added to the target's history.
 */
export function RunQuery(connID: string, req: $models.QueryRequest, sudoPassword: string): $CancellablePromise<$models.QueryResult> {
    return $Call.ByID(1477581034, connID, req, sudoPassword);
}

/**
 * SaveSnippet creates or updates a saved query.
 */
export function SaveSnippet(sn: $models.Snippet): $CancellablePromise<$models.Snippet> {
    return $Call.ByID(1449639777, sn);
}

/**
 * SaveTarget creates or updates a target. password is stored in the OS
 * keychain when setPassword is true ("" removes it).
 */
export function SaveTarget(connID: string, $in: $models.TargetInput, password: string, setPassword: boolean): $CancellablePromise<$models.Target> {
    return $Call.ByID(2632169525, connID, $in, password, setPassword);
}

/**
 * SetSlowLog turns the MySQL slow query log on/off and sets long_query_time
 * (seconds, 0–3600) at runtime (SET GLOBAL; not persisted in my.cnf).
 */
export function SetSlowLog(connID: string, targetID: string, enabled: boolean, longQueryTime: number, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(524015580, connID, targetID, enabled, longQueryTime, sudoPassword);
}

/**
 * SlowLogTail returns the last lines (10–5000) of the MySQL slow log file.
 */
export function SlowLogTail(connID: string, targetID: string, lines: number, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(2195970296, connID, targetID, lines, sudoPassword);
}

/**
 * SlowQueries returns the most expensive statements: pg_stat_statements
 * (Postgres, in database or the default one) or performance_schema digests
 * (MySQL), ordered by total | mean | calls | max time.
 */
export function SlowQueries(connID: string, targetID: string, database: string, order: string, sudoPassword: string): $CancellablePromise<$models.SlowReport> {
    return $Call.ByID(522114772, connID, targetID, database, order, sudoPassword);
}

/**
 * Snippets lists saved queries for an engine ("" = all).
 */
export function Snippets(engine: string): $CancellablePromise<$models.Snippet[] | null> {
    return $Call.ByID(2524012643, engine);
}

/**
 * Tables lists the largest tables of a database ("" = all user databases
 * on MySQL, the default database on Postgres).
 */
export function Tables(connID: string, targetID: string, database: string, sudoPassword: string): $CancellablePromise<$models.TableInfo[] | null> {
    return $Call.ByID(376585920, connID, targetID, database, sudoPassword);
}

/**
 * Targets lists the detected and saved targets of a server. Detection runs
 * when it hasn't yet this session (or is older than 10 minutes).
 */
export function Targets(connID: string): $CancellablePromise<$models.Target[] | null> {
    return $Call.ByID(3063837677, connID);
}
