// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Activity {
    "sessions": Session[] | null;
    "locks": LockWait[] | null;
    "maxConnections": number;
}

export interface DatabaseInfo {
    "name": string;
    "owner": string;
    "encoding": string;
    "collation": string;

    /**
     * bytes, -1 = unknown (no access)
     */
    "size": number;
    "tables": number;
    "connections": number;
    "allowConn": boolean;

    /**
     * 0..1, -1 = unknown
     */
    "cacheHit": number;
    "system": boolean;
}

/**
 * Detection is the result of scanning a server for database engines.
 */
export interface Detection {
    "engines": EngineInfo[] | null;
    "targets": Target[] | null;

    /**
     * Docker: none (not installed) | ok | sudo (usable through sudo) |
     * denied (no access: sudo password needed) | down (daemon not running).
     */
    "docker": string;
    "containers": number;
}

/**
 * EngineInfo describes what was found on the host for one engine.
 */
export interface EngineInfo {
    "engine": string;

    /**
     * path of psql / mysql / redis-cli ("" = missing)
     */
    "client": string;
    "clientVersion": string;
    "serverVersion": string;

    /**
     * mariadb | mysql (MySQL engine)
     */
    "flavor": string;
    "units": UnitInfo[] | null;
    "ports": number[] | null;
    "running": boolean;

    /**
     * a server is installed on the host
     */
    "installed": boolean;
}

/**
 * HistoryEntry is a past query run of a target.
 */
export interface HistoryEntry {
    "id": string;

    /**
     * unix ms
     */
    "ts": number;
    "sql": string;
    "database": string;
    "ok": boolean;
    "error": string;
    "elapsed": number;
    "rows": number;
    "readOnly": boolean;
}

export interface InfoSection {
    "name": string;
    "items": KV[] | null;
}

export interface KV {
    "name": string;
    "value": string;
}

export interface LockWait {
    "pid": number;
    "user": string;
    "database": string;
    "lockType": string;
    "mode": string;
    "relation": string;
    "blockedBy": number[] | null;
    "waiting": number;
    "query": string;
}

export interface MyOverview {
    /**
     * mariadb | mysql
     */
    "flavor": string;
    "versionComment": string;
    "maxConnections": number;
    "threadsConnected": number;
    "threadsRunning": number;
    "maxUsedConnections": number;
    "questions": number;
    "slowQueries": number;
    "connections": number;
    "abortedConnects": number;
    "bufferPoolSize": number;

    /**
     * -1 unknown
     */
    "bufferPoolHitRatio": number;

    /**
     * 0..1
     */
    "bufferPoolUsed": number;
    "databases": number;
    "slowLog": SlowLogSettings;

    /**
     * replica status fields (empty when not a replica)
     */
    "replication": KV[] | null;
    "settings": KV[] | null;
}

export interface NameCount {
    "name": string;
    "count": number;
}

/**
 * Overview is the status summary of a target; exactly one of the engine
 * sections is set.
 */
export interface Overview {
    "engine": string;
    "version": string;

    /**
     * seconds
     */
    "uptime": number;
    "postgres": PgOverview | null;
    "mysql": MyOverview | null;
    "redis": RedisOverview | null;
}

export interface PgOverview {
    "versionNum": number;
    "startTime": string;
    "maxConnections": number;
    "connections": number;
    "byState": NameCount[] | null;

    /**
     * -1 unknown
     */
    "cacheHitRatio": number;
    "inRecovery": boolean;

    /**
     * standby: seconds since last replayed transaction, -1 n/a
     */
    "replayDelay": number;
    "databases": DatabaseInfo[] | null;
    "totalSize": number;
    "xactCommit": number;
    "xactRollback": number;
    "deadlocks": number;
    "locksWaiting": number;

    /**
     * seconds (active queries)
     */
    "longestQuery": number;
    "idleInTx": number;
    "replicas": PgReplica[] | null;

    /**
     * extension installed in the default database
     */
    "statStatements": boolean;
    "settings": KV[] | null;
}

export interface PgReplica {
    "pid": number;
    "user": string;
    "app": string;
    "client": string;
    "state": string;
    "syncState": string;

    /**
     * -1 unknown
     */
    "lagBytes": number;

    /**
     * seconds
     */
    "replayLag": number;
}

/**
 * QueryRequest is a query-runner request (Postgres, MySQL).
 */
export interface QueryRequest {
    "targetId": string;

    /**
     * "" = target default
     */
    "database": string;
    "sql": string;

    /**
     * AllowWrite runs without the read-only guard (the UI confirms first).
     */
    "allowWrite": boolean;

    /**
     * statement timeout, default 30, max 3600
     */
    "timeoutSec": number;

    /**
     * rows kept per result, default 1000, max 10000
     */
    "maxRows": number;
}

/**
 * QueryResult is the outcome of a run. Statements before a failing one
 * keep their results; ErrorIndex/Error describe the failure.
 */
export interface QueryResult {
    "statements": StatementResult[] | null;

    /**
     * ms
     */
    "elapsed": number;
    "readOnly": boolean;

    /**
     * 1-based, 0 = none
     */
    "errorIndex": number;
    "error": string;

    /**
     * OutputTruncated: the output was too large and got cut.
     */
    "outputTruncated": boolean;
}

export interface RedisDB {
    "db": number;
    "keys": number;
    "expires": number;

    /**
     * ms
     */
    "avgTtl": number;
}

export interface RedisOverview {
    "mode": string;
    "role": string;
    "connectedClients": number;
    "blockedClients": number;
    "maxClients": number;
    "usedMemory": number;
    "usedMemoryPeak": number;
    "usedMemoryRss": number;
    "maxMemory": number;
    "maxMemoryPolicy": string;
    "fragRatio": number;
    "evictedKeys": number;
    "expiredKeys": number;
    "opsPerSec": number;
    "totalCommands": number;
    "hits": number;
    "misses": number;

    /**
     * -1 unknown
     */
    "hitRatio": number;
    "rdbLastSave": number;
    "rdbLastStatus": string;
    "rdbChanges": number;
    "rdbSaving": boolean;
    "aofEnabled": boolean;
    "aofLastStatus": string;
    "aofRewriting": boolean;
    "connectedSlaves": number;
    "masterHost": string;
    "masterLinkStatus": string;
    "replicas": string[] | null;
    "keyspace": RedisDB[] | null;
    "slowlog": RedisSlow[] | null;
    "slowlogError": string;

    /**
     * CONFIG disabled/renamed
     */
    "configError": string;
    "sections": InfoSection[] | null;
}

/**
 * RedisResult is the reply of a console command.
 */
export interface RedisResult {
    "command": string;

    /**
     * redis-cli formatted reply
     */
    "output": string;
    "isError": boolean;

    /**
     * the command was classified as changing data/state
     */
    "write": boolean;
    "elapsed": number;
}

export interface RedisSlow {
    "id": number;

    /**
     * unix seconds
     */
    "ts": number;

    /**
     * microseconds
     */
    "duration": number;
    "command": string;
    "client": string;
    "name": string;
}

export interface Session {
    /**
     * pid (Postgres) / thread id (MySQL)
     */
    "id": number;
    "user": string;
    "database": string;
    "app": string;
    "client": string;
    "state": string;

    /**
     * MySQL command (Query, Sleep…)
     */
    "command": string;
    "wait": string;
    "backendType": string;

    /**
     * seconds in current query/state, -1 none
     */
    "duration": number;

    /**
     * seconds in transaction, -1 none
     */
    "xactAge": number;

    /**
     * seconds connected
     */
    "age": number;
    "query": string;
    "blockedBy": number[] | null;
}

export interface SlowLogSettings {
    "enabled": boolean;
    "longQueryTime": number;
    "file": string;

    /**
     * FILE, TABLE, FILE,TABLE, NONE
     */
    "output": string;
    "notUsingIndexes": boolean;
}

export interface SlowQuery {
    "query": string;
    "calls": number;
    "totalMs": number;
    "meanMs": number;
    "maxMs": number;
    "rows": number;
    "database": string;
    "user": string;

    /**
     * -1 unknown
     */
    "hitRatio": number;
}

/**
 * SlowReport lists the most expensive queries and how they are collected.
 */
export interface SlowReport {
    /**
     * Source: pg_stat_statements | performance_schema | none
     */
    "source": string;

    /**
     * Reason when Source is none: notPreloaded | notInstalled | psDisabled | error
     */
    "reason": string;
    "detail": string;
    "database": string;
    "preloaded": boolean;
    "queries": SlowQuery[] | null;

    /**
     * MySQL
     */
    "slowLog": SlowLogSettings;
}

/**
 * Snippet is a saved query.
 */
export interface Snippet {
    "id": string;
    "name": string;

    /**
     * postgres | mysql | redis
     */
    "engine": string;
    "sql": string;
    "updated": number;
}

/**
 * StatementResult is the outcome of one statement of a query run.
 */
export interface StatementResult {
    /**
     * 1-based statement number
     */
    "index": number;

    /**
     * statement text (shortened)
     */
    "sql": string;

    /**
     * first keyword (SELECT, UPDATE…)
     */
    "command": string;

    /**
     * HasRows: the statement returned a result set (possibly empty).
     */
    "hasRows": boolean;
    "columns": string[] | null;

    /**
     * nil cell = SQL NULL
     */
    "rows": ((string | null)[] | null)[] | null;

    /**
     * RowCount: rows returned (result sets) or affected (DML); -1 unknown.
     */
    "rowCount": number;

    /**
     * more rows than returned
     */
    "truncated": boolean;
}

export interface TableInfo {
    "schema": string;
    "name": string;

    /**
     * table, matview, partitioned / MySQL engine
     */
    "kind": string;

    /**
     * estimate
     */
    "rows": number;
    "totalBytes": number;
    "dataBytes": number;
    "indexBytes": number;

    /**
     * MySQL data_free
     */
    "freeBytes": number;

    /**
     * Postgres
     */
    "deadRows": number;
    "lastVacuum": string;
    "lastUpdate": string;
}

/**
 * Target is a database server the app can talk to: detected on the host or
 * in a container, or added by the user.
 */
export interface Target {
    "id": string;
    "server": string;

    /**
     * postgres | mysql | redis
     */
    "engine": string;
    "name": string;

    /**
     * local | docker
     */
    "mode": string;

    /**
     * docker mode
     */
    "container": string;

    /**
     * peer | password
     */
    "auth": string;

    /**
     * "" = local socket / default
     */
    "host": string;

    /**
     * 0 = default
     */
    "port": number;
    "user": string;

    /**
     * default database ("" = engine default)
     */
    "database": string;

    /**
     * Detected targets come from Detect; Saved ones have a stored record
     * (a user-defined target, or edited settings of a detected one).
     */
    "detected": boolean;
    "saved": boolean;
    "hasPassword": boolean;

    /**
     * from detection, when known
     */
    "version": string;
    "running": boolean;

    /**
     * docker image
     */
    "image": string;
}

/**
 * TargetInput is what the UI sends to create or edit a target.
 */
export interface TargetInput {
    /**
     * "" = new
     */
    "id": string;
    "engine": string;
    "name": string;
    "mode": string;
    "container": string;
    "auth": string;
    "host": string;
    "port": number;
    "user": string;
    "database": string;
}

/**
 * UnitInfo is a systemd unit of a database engine.
 */
export interface UnitInfo {
    "name": string;
    "active": string;
    "sub": string;
}
