// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteBackup deletes one stored backup (and its manifest).
 */
export function DeleteBackup(connID: string, jobID: string, key: string, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(1429995890, connID, jobID, key, sudoPassword);
}

/**
 * DeleteDestination removes a destination that no job uses. Stored
 * backups are not touched.
 */
export function DeleteDestination(id: string): $CancellablePromise<void> {
    return $Call.ByID(1395346172, id);
}

/**
 * DeleteJob removes a job and its secrets. Backups already stored at the
 * destination are kept.
 */
export function DeleteJob(connID: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(375927071, connID, id);
}

/**
 * Detect checks which backup tools exist on the server and lists Docker
 * volumes (when docker is usable).
 */
export function Detect(connID: string): $CancellablePromise<$models.Detection> {
    return $Call.ByID(3219324680, connID);
}

/**
 * Download asks where to save a backup and copies it to this computer,
 * decrypted (decrypt) or as stored. Returns the job id, or "" if the user
 * cancelled the dialog.
 */
export function Download(connID: string, jobID: string, key: string, decrypt: boolean, passphrase: string, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(71444443, connID, jobID, key, decrypt, passphrase, sudoPassword);
}

/**
 * History lists backup and restore runs of a server (jobID "" = all jobs).
 */
export function History(connID: string, jobID: string, limit: number): $CancellablePromise<$models.Run[] | null> {
    return $Call.ByID(702415505, connID, jobID, limit);
}

/**
 * ListBackups lists the backups stored for a job, newest first.
 */
export function ListBackups(connID: string, jobID: string, sudoPassword: string): $CancellablePromise<$models.BackupItem[] | null> {
    return $Call.ByID(3116551258, connID, jobID, sudoPassword);
}

/**
 * ListDestinations returns every destination (secrets are never returned).
 */
export function ListDestinations(): $CancellablePromise<$models.Destination[] | null> {
    return $Call.ByID(1995031994);
}

/**
 * ListJobs returns the server's backup jobs.
 */
export function ListJobs(connID: string): $CancellablePromise<$models.Job[] | null> {
    return $Call.ByID(2061934471, connID);
}

/**
 * PickLocalFolder opens a native folder picker ("" when cancelled).
 */
export function PickLocalFolder(title: string): $CancellablePromise<string> {
    return $Call.ByID(3707551417, title);
}

/**
 * PreviewSchedule validates a schedule and returns its next n runs.
 */
export function PreviewSchedule(sched: $models.Schedule, n: number): $CancellablePromise<$models.CronPreview> {
    return $Call.ByID(1788767720, sched, n);
}

/**
 * Restore restores a backup onto the server as a job (PermRestore). The
 * payload is verified against its manifest before anything is changed.
 */
export function Restore(connID: string, opts: $models.RestoreOptions, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(3855852375, connID, opts, sudoPassword);
}

/**
 * RevealPassphrase returns a job's encryption passphrase (to keep a copy
 * in a password manager). Audited.
 */
export function RevealPassphrase(connID: string, id: string): $CancellablePromise<string> {
    return $Call.ByID(2058989870, connID, id);
}

/**
 * RunLog returns the stored output of a finished run.
 */
export function RunLog(connID: string, runID: string): $CancellablePromise<string> {
    return $Call.ByID(438485146, connID, runID);
}

/**
 * RunNow starts a backup job now and returns the core job id.
 */
export function RunNow(connID: string, jobID: string, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(3548561072, connID, jobID, sudoPassword);
}

/**
 * SaveDestination creates or updates a destination. secret is the S3
 * secret key; "" keeps the stored one.
 */
export function SaveDestination(d: $models.Destination, secret: string): $CancellablePromise<$models.Destination> {
    return $Call.ByID(1252237470, d, secret);
}

/**
 * SaveJob creates or updates a backup job.
 */
export function SaveJob(connID: string, j: $models.Job, sec: $models.JobSecrets): $CancellablePromise<$models.Job> {
    return $Call.ByID(198635293, connID, j, sec);
}

/**
 * Status returns per-job last success/failure and next run for a server.
 */
export function Status(connID: string): $CancellablePromise<$models.JobStatus[] | null> {
    return $Call.ByID(2095894553, connID);
}

/**
 * TestDestination writes, reads back and deletes a small probe object.
 * connID is required for server destinations. secret "" uses the stored one.
 */
export function TestDestination(connID: string, d: $models.Destination, secret: string): $CancellablePromise<$models.DestTest> {
    return $Call.ByID(494214929, connID, d, secret);
}

/**
 * Verify downloads a backup, decrypts it and checks its checksums and
 * structure without restoring anything. passphrase "" uses the stored one.
 */
export function Verify(connID: string, jobID: string, key: string, passphrase: string, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(915386642, connID, jobID, key, passphrase, sudoPassword);
}
