// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apperr$0 from "../../internal/apperr/models.js";

/**
 * BackupItem is one stored backup of a job.
 */
export interface BackupItem {
    "key": string;
    "name": string;

    /**
     * unix ms (from the name)
     */
    "time": number;

    /**
     * stored size
     */
    "size": number;
    "encrypted": boolean;

    /**
     * data + manifest present
     */
    "complete": boolean;
    "manifest": Manifest | null;
}

/**
 * CronPreview is the cron expression of a schedule and its next runs.
 */
export interface CronPreview {
    "cron": string;

    /**
     * unix ms
     */
    "next": number[] | null;
}

/**
 * DestTest is the result of a successful destination test.
 */
export interface DestTest {
    "millis": number;

    /**
     * NeedsRoot: the server directory is only writable with sudo.
     */
    "needsRoot": boolean;
}

/**
 * Destination is where backups are stored. Destinations are global: any
 * server's jobs may use them. The S3 secret key lives in the keychain.
 */
export interface Destination {
    "id": string;
    "name": string;

    /**
     * local | server | s3
     */
    "type": string;

    /**
     * Path is the folder on this computer (local) or on the backed-up
     * server (server).
     */
    "path": string;

    /**
     * S3-compatible storage.
     * host[:port], no scheme
     */
    "endpoint": string;
    "region": string;
    "bucket": string;
    "prefix": string;
    "accessKey": string;
    "pathStyle": boolean;
    "useTls": boolean;

    /**
     * HasSecret reports whether the S3 secret key is stored in the keychain.
     */
    "hasSecret": boolean;
    "created": number;
    "updated": number;
}

/**
 * Detection lists what the server offers for backups.
 */
export interface Detection {
    "tools": string[] | null;
    "volumes": string[] | null;
}

/**
 * Job is a backup definition for one server.
 */
export interface Job {
    "id": string;
    "server": string;
    "name": string;
    "type": string;
    "enabled": boolean;

    /**
     * Folder is "<server-slug>/<job-slug>", fixed when the job is created so
     * renaming a job doesn't orphan its backups.
     */
    "folder": string;

    /**
     * files
     */
    "paths": string[] | null;
    "excludes": string[] | null;

    /**
     * Sudo runs the backup command as root (files, custom, password-auth
     * databases). Peer/socket database auth, volumes and redis always do.
     */
    "sudo": boolean;

    /**
     * postgres / mysql / redis
     * "" = all databases
     */
    "database": string;

    /**
     * peer (postgres via sudo -u postgres, mysql root socket) | password
     */
    "authMode": string;
    "dbUser": string;
    "dbHost": string;
    "dbPort": number;

    /**
     * HasDBPassword reports whether a database/redis password is stored.
     */
    "hasDbPassword": boolean;

    /**
     * docker volume
     */
    "volume": string;
    "stopContainers": boolean;

    /**
     * redis
     * "" = ask redis (CONFIG GET dir/dbfilename)
     */
    "redisDumpPath": string;

    /**
     * custom
     */
    "command": string;
    "ext": string;
    "restoreCommand": string;

    /**
     * none | gzip | zstd
     */
    "compression": string;
    "encrypt": boolean;

    /**
     * HasPassphrase reports whether the encryption passphrase is stored.
     */
    "hasPassphrase": boolean;

    /**
     * VerifyAfter re-reads the uploaded backup and checks its hash.
     */
    "verifyAfter": boolean;
    "schedule": Schedule;
    "retention": Retention;
    "destination": string;
    "preHook": string;
    "postHook": string;
    "timeoutMin": number;
    "created": number;
    "updated": number;
}

/**
 * JobSecrets carries secrets entered in the job editor ("" = keep).
 */
export interface JobSecrets {
    "passphrase": string;
    "dbPassword": string;

    /**
     * ClearDBPassword removes the stored database password.
     */
    "clearDbPassword": boolean;
}

/**
 * JobStatus summarizes a job's recent runs (used by the health module:
 * "last successful backup age").
 */
export interface JobStatus {
    "jobId": string;
    "name": string;
    "type": string;
    "enabled": boolean;
    "cron": string;

    /**
     * unix ms (start)
     */
    "lastRun": number;
    "lastStatus": string;

    /**
     * unix ms (finish)
     */
    "lastSuccess": number;
    "lastFailure": number;
    "lastSize": number;
    "lastError": apperr$0.Error | null;

    /**
     * unix ms, 0 = none
     */
    "nextRun": number;
    "running": boolean;

    /**
     * core job id
     */
    "runningJob": string;
}

/**
 * Manifest is the .manifest.json sidecar of a backup object. It never
 * contains secrets.
 */
export interface Manifest {
    "format": number;
    "jobId": string;
    "jobName": string;
    "type": string;
    "server": string;
    "serverName": string;
    "database"?: string;
    "volume"?: string;
    "paths"?: string[] | null;

    /**
     * tar | pg-custom | sql | rdb | raw
     */
    "dumpFormat": string;

    /**
     * unix ms
     */
    "created": number;
    "object": string;

    /**
     * payload (after compression, before encryption)
     */
    "size": number;

    /**
     * of the payload
     */
    "sha256": string;
    "objectSize": number;

    /**
     * of the stored bytes
     */
    "objectSha256": string;
    "compression": string;
    "encrypted": boolean;
    "encryption"?: string;
    "tools": { [_ in string]?: string } | null;
    "appVersion": string;
}

/**
 * RestoreOptions describes where and how to restore a backup.
 */
export interface RestoreOptions {
    "jobId": string;
    "key": string;

    /**
     * Target: files → staging | original; redis → staging | replace;
     * custom → staging | command. Ignored for databases and volumes.
     */
    "target": string;

    /**
     * Dir is the staging directory (files/redis/custom staging).
     */
    "dir": string;

    /**
     * Database is the target database (postgres custom dumps, mysql single db).
     */
    "database": string;
    "createDb": boolean;

    /**
     * Volume is the target Docker volume (created if missing).
     */
    "volume": string;
    "clearVolume": boolean;
    "stopContainers": boolean;

    /**
     * Passphrase overrides the stored one (backups made before a change).
     */
    "passphrase": string;

    /**
     * TempDir is where the verified payload is staged on the server.
     */
    "tempDir": string;
}

/**
 * Retention limits how many backups a job keeps at its destination.
 */
export interface Retention {
    /**
     * 0 = unlimited
     */
    "keepLast": number;

    /**
     * 0 = unlimited
     */
    "maxAgeDays": number;
}

/**
 * Run is one backup or restore run.
 */
export interface Run {
    "id": string;

    /**
     * backup | backup.restore
     */
    "kind": string;
    "server": string;
    "jobId": string;

    /**
     * unix ms
     */
    "started": number;

    /**
     * 0 while running
     */
    "finished": number;

    /**
     * running | ok | failed | cancelled
     */
    "status": string;
    "actor": string;
    "jobName": string;
    "type": string;

    /**
     * manual | schedule | missed | restore
     */
    "trigger": string;
    "coreJob": string;
    "destination": string;
    "key": string;
    "location": string;
    "size": number;
    "objectSize": number;
    "sha256": string;
    "objectSha256": string;
    "encrypted": boolean;
    "compression": string;
    "deleted": number;
    "warnings": string[] | null;
    "error": apperr$0.Error | null;
}

export interface RunEvent {
    "server": string;
    "jobId": string;
    "runId": string;
    "status": string;
}

/**
 * Schedule is the user-facing schedule; Cron is derived from it.
 */
export interface Schedule {
    /**
     * manual | hourly | daily | weekly | cron
     */
    "mode": string;

    /**
     * hourly: minute past the hour
     */
    "minute": number;

    /**
     * daily/weekly: "HH:MM"
     */
    "time": string;

    /**
     * weekly: 0=Sunday … 6=Saturday
     */
    "weekday": number;

    /**
     * cron mode: 5-field expression; otherwise derived
     */
    "cron": string;
}
