// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AccessEntry {
    /**
     * IP or CIDR, canonical
     */
    "addr": string;

    /**
     * block | allow
     */
    "kind": string;

    /**
     * Source is what enforces it: ufw | firewalld | iptables | fail2ban.
     */
    "source": string;

    /**
     * fail2ban jail
     */
    "jail": string;

    /**
     * "" = every port, else "22/tcp", "80,443/tcp"…
     */
    "ports": string;
    "comment": string;

    /**
     * added by Server Manager
     */
    "managed": boolean;

    /**
     * Ref identifies the rule for removal (ufw "show added" line, firewalld
     * zone / rich rule, iptables -S line, jail name).
     */
    "ref": string;
}

export interface AccessRequest {
    "addrs": string[] | null;
    "comment": string;

    /**
     * Temporary (block): ban with fail2ban, which lifts it after the jail's
     * ban time, instead of a permanent firewall rule.
     */
    "temporary": boolean;

    /**
     * Ports (allow): "" = every port, "ssh" = the SSH ports, or a list/range.
     */
    "ports": string;
}

export interface AccessResult {
    "applied": string[] | null;
    "skipped": AccessSkip[] | null;

    /**
     * Saved: iptables persistence method used; NotSaved: the rules are live
     * but will not survive a reboot.
     */
    "saved": string;
    "notSaved": boolean;
}

export interface AccessSkip {
    "addr": string;

    /**
     * Reason: invalid | self | local | tooBroad | allowlisted | already |
     * cidrTemp | failed | gone | conflict
     */
    "reason": string;
    "detail": string;
}

export interface AccessState {
    /**
     * Backend is the firewall the app writes to: firewalld (running) › ufw ›
     * iptables › none.
     */
    "backend": string;

    /**
     * Active: that firewall is filtering (an inactive ufw keeps rules but
     * does not apply them).
     */
    "active": boolean;
    "clientIp": string;
    "sshPorts": number[] | null;
    "entries": AccessEntry[] | null;
    "fail2ban": Fail2banInfo;

    /**
     * Persist: how iptables rules survive a reboot ("" = they don't).
     */
    "persist": string;

    /**
     * SSHLocked: SSH is reachable only from allowlisted addresses.
     */
    "sshLocked": boolean;

    /**
     * CanLock: the backend supports the SSH lock (ufw, firewalld).
     */
    "canLock": boolean;

    /**
     * DefaultDeny: incoming traffic not matched by a rule is dropped.
     */
    "defaultDeny": boolean;
    "docker": boolean;
}

export interface AccountEvent {
    "time": number;
    "tool": string;

    /**
     * user | group | password
     */
    "kind": string;
    "message": string;
}

/**
 * AuthorizedKey is one line of an authorized_keys file.
 */
export interface AuthorizedKey {
    "line": number;
    "type": string;
    "bits": number;
    "comment": string;
    "fingerprint": string;
    "options": string[] | null;
    "invalid": boolean;

    /**
     * only for invalid lines (truncated)
     */
    "raw": string;

    /**
     * InUse: the current session authenticated with this key ("yes"), maybe
     * did (agent keys: "maybe") or not ("").
     */
    "inUse": string;
}

/**
 * Check is one item of the security checklist. The UI renders the title
 * from `sec.chk.<id>`, the finding from `sec.chk.<id>.<code>` (with Params)
 * and the recommendation from `sec.fix.<id>`.
 */
export interface Check {
    "id": string;

    /**
     * ok | warn | crit | info | unknown
     */
    "status": string;
    "code": string;
    "params": { [_ in string]?: string } | null;
    "items": string[] | null;
    "weight": number;

    /**
     * Tab is the panel tab where the issue can be fixed.
     */
    "tab": string;
}

export interface EventsResult {
    /**
     * journal | file | none
     */
    "source": string;
    "sourcePath": string;
    "since": number;
    "now": number;
    "failedTotal": number;
    "failedByIp": FailedByIP[] | null;
    "failedByUser": FailedByUser[] | null;
    "logins": LoginEvent[] | null;
    "sudo": SudoEvent[] | null;
    "accounts": AccountEvent[] | null;
    "last": LastEntry[] | null;
    "lastb": LastEntry[] | null;
    "fail2ban": Fail2banStatus;
    "limited": boolean;
    "truncated": boolean;
    "loginUser": string;
}

export interface Fail2banConfig {
    "maxRetry": number;

    /**
     * seconds
     */
    "findTime": number;

    /**
     * seconds, -1 = forever
     */
    "banTime": number;
    "increment": boolean;

    /**
     * seconds, cap of incremental bans
     */
    "maxTime": number;
    "recidive": boolean;
    "aggressive": boolean;
    "ignoreIp": string[] | null;
}

export interface Fail2banInfo {
    "installed": boolean;
    "running": boolean;
    "version": string;
    "jails": string[] | null;
    "sshJail": string;

    /**
     * Managed: the app's jail file exists (Config then comes from it).
     */
    "managed": boolean;
    "config": Fail2banConfig;

    /**
     * JournalOnly: no auth log file, sshd logs only to the journal (the sshd
     * jail then needs backend = systemd).
     */
    "journalOnly": boolean;
    "pkgManager": string;
}

export interface Fail2banJail {
    "name": string;
    "currentlyFailed": number;
    "totalFailed": number;
    "currentlyBanned": number;
    "totalBanned": number;
    "banned": string[] | null;
}

export interface Fail2banStatus {
    "installed": boolean;
    "running": boolean;
    "jails": Fail2banJail[] | null;
}

export interface FailedByIP {
    "ip": string;
    "count": number;
    "users": string[] | null;

    /**
     * attempts with non-existent users
     */
    "invalid": number;
    "first": number;
    "last": number;
}

export interface FailedByUser {
    "user": string;
    "count": number;
    "ips": number;
    "invalid": boolean;
    "first": number;
    "last": number;
}

export interface FirewallBackend {
    /**
     * ufw | firewalld | iptables | nftables
     */
    "name": string;
    "installed": boolean;
    "active": boolean;
    "version": string;
}

export interface FirewallInfo {
    /**
     * Primary is the backend the app manages: firewalld when running, else
     * ufw, else iptables, else nftables (read-only), else "none".
     */
    "primary": string;
    "backends": FirewallBackend[] | null;
    "sshPorts": number[] | null;

    /**
     * ClientIP is this session's address as seen by the server.
     */
    "clientIp": string;
}

export interface FirewalldStatus {
    "installed": boolean;
    "running": boolean;
    "defaultZone": string;
    "zones": string[] | null;
    "details": FirewalldZone[] | null;
    "sshPorts": number[] | null;
}

export interface FirewalldZone {
    "name": string;
    "active": boolean;
    "default": boolean;
    "target": string;
    "interfaces": string[] | null;
    "sources": string[] | null;
    "services": string[] | null;
    "ports": string[] | null;
    "protocols": string[] | null;
    "forwardPorts": string[] | null;
    "masquerade": boolean;
    "richRules": string[] | null;
}

export interface IptChain {
    "name": string;
    "policy": string;
    "rules": IptRule[] | null;
}

export interface IptRule {
    "num": number;
    "pkts": string;
    "bytes": string;
    "target": string;
    "proto": string;
    "in": string;
    "out": string;
    "source": string;
    "dest": string;
    "extra": string;

    /**
     * from iptables -S (used to confirm deletes)
     */
    "spec": string;
    "comment": string;
}

export interface IptablesStatus {
    "installed": boolean;
    "v6": boolean;

    /**
     * nf_tables | legacy
     */
    "variant": string;
    "chains": IptChain[] | null;
    "raw": string;

    /**
     * Persist is how rules are saved: netfilter-persistent | rules.v4 |
     * sysconfig | openrc | "" (not persistent).
     */
    "persist": string;

    /**
     * ManagedBy warns that another tool owns the rules (ufw, firewalld).
     */
    "managedBy": string;
}

export interface KeyList {
    "user": string;
    "home": string;
    "path": string;
    "exists": boolean;
    "keys": AuthorizedKey[] | null;
    "isLogin": boolean;

    /**
     * Perm problems found (e.g. "~/.ssh 755", "owner root").
     */
    "problems": string[] | null;

    /**
     * PasswordAuth is sshd's effective PasswordAuthentication ("" if unknown).
     */
    "passwordAuth": string;
}

export interface LastEntry {
    "user": string;
    "tty": string;
    "host": string;
    "time": number;
    "detail": string;
}

export interface LinuxGroup {
    "name": string;
    "gid": number;
    "members": string[] | null;
    "system": boolean;
}

export interface LinuxUser {
    "name": string;
    "uid": number;
    "gid": number;
    "gecos": string;
    "home": string;
    "shell": string;
    "primaryGroup": string;

    /**
     * supplementary groups
     */
    "groups": string[] | null;

    /**
     * uid 0 or member of sudo/wheel/admin
     */
    "admin": boolean;

    /**
     * PwStatus: P (usable password), L (locked), NP (empty password!),
     * NS (no password set: key-only), "" (unknown without root).
     */
    "pwStatus": string;
    "locked": boolean;
    "expired": boolean;
    "system": boolean;

    /**
     * shell is not nologin/false
     */
    "canLogin": boolean;
    "lastLogin": number;
    "lastFrom": string;
    "isLogin": boolean;
}

/**
 * Listener is one listening socket.
 */
export interface Listener {
    /**
     * tcp | udp
     */
    "proto": string;
    "address": string;
    "port": number;

    /**
     * Scope: any (all interfaces) | loopback | specific (one address).
     */
    "scope": string;
    "public": boolean;
    "process": string;
    "pids": number[] | null;
    "v6": boolean;
}

export interface LoginEvent {
    "time": number;
    "user": string;
    "ip": string;
    "method": string;

    /**
     * New: no earlier successful login from this IP (window + wtmp history).
     */
    "new": boolean;
}

export interface NewIptRule {
    "v6": boolean;

    /**
     * INPUT | OUTPUT | FORWARD
     */
    "chain": string;

    /**
     * ACCEPT | DROP | REJECT
     */
    "target": string;

    /**
     * tcp | udp | icmp | all
     */
    "proto": string;

    /**
     * "", "22", "8000:8100"
     */
    "port": string;

    /**
     * any | IP | CIDR
     */
    "source": string;
    "interface": string;
    "comment": string;

    /**
     * insert at the top instead of appending
     */
    "top": boolean;
    "force": boolean;
}

/**
 * NewUFWRule describes a rule to add.
 */
export interface NewUFWRule {
    /**
     * allow | deny | reject | limit
     */
    "action": string;

    /**
     * in | out
     */
    "direction": string;

    /**
     * "", "22", "8000:8100", "80,443"
     */
    "port": string;

    /**
     * tcp | udp | any
     */
    "proto": string;

    /**
     * any | IP | CIDR
     */
    "from": string;

    /**
     * any | IP | CIDR
     */
    "to": string;
    "interface": string;
    "comment": string;

    /**
     * 0 = append, N = insert at N
     */
    "position": number;

    /**
     * accept that it may block SSH
     */
    "force": boolean;
}

export interface NewUser {
    "name": string;
    "gecos": string;
    "shell": string;
    "createHome": boolean;
    "admin": boolean;

    /**
     * optional; fed on stdin to chpasswd
     */
    "password": string;

    /**
     * optional public key
     */
    "sshKey": string;
}

export interface Overview {
    "score": number;
    "checks": Check[] | null;
    "logins": LastEntry[] | null;

    /**
     * no root: some checks unknown
     */
    "limited": boolean;
    "distro": string;
    "firewall": string;
    "time": number;
}

/**
 * PortCheck tells whether the active firewall lets a port in.
 */
export interface PortCheck {
    "backend": string;
    "active": boolean;

    /**
     * yes | no | unknown
     */
    "allowed": string;
}

export interface PortsResult {
    /**
     * ss | netstat
     */
    "tool": string;
    "listeners": Listener[] | null;

    /**
     * Limited: process names of other users are hidden (no root).
     */
    "limited": boolean;
}

/**
 * SSHConfig is the effective sshd configuration (from `sshd -T`) plus the
 * context the UI needs to change it safely.
 */
export interface SSHConfig {
    "version": string;
    "ports": number[] | null;
    "listenAddresses": string[] | null;
    "permitRootLogin": string;
    "passwordAuthentication": string;
    "pubkeyAuthentication": string;
    "kbdInteractiveAuthentication": string;
    "usePam": string;
    "maxAuthTries": number;
    "allowUsers": string[] | null;
    "allowGroups": string[] | null;
    "denyUsers": string[] | null;
    "denyGroups": string[] | null;
    "x11Forwarding": string;
    "clientAliveInterval": number;
    "clientAliveCountMax": number;
    "authorizedKeysFile": string;

    /**
     * Mode is "dropin" (sshd_config includes sshd_config.d first; the app
     * writes ConfigPath = sshd_config.d/00-server-manager.conf) or "main"
     * (a managed block at the top of sshd_config).
     */
    "mode": string;
    "configPath": string;

    /**
     * Managed lists the directives currently set by the app.
     */
    "managed": { [_ in string]?: string[] | null } | null;

    /**
     * Files are the config files that were read (for display).
     */
    "files": string[] | null;
    "sessionPort": number;
    "loginUser": string;
    "loginIsRoot": boolean;

    /**
     * password | key | agent
     */
    "authType": string;
    "loginKeyCount": number;

    /**
     * Enforcing | Permissive | Disabled | ""
     */
    "selinux": string;
}

/**
 * SSHConfirm carries the user's explicit acknowledgements for risky changes.
 */
export interface SSHConfirm {
    /**
     * disable password login although no key is installed
     */
    "noKeys": boolean;

    /**
     * restrict root login while connected as root
     */
    "rootLogin": boolean;

    /**
     * disable public keys while connected with a key
     */
    "pubkeySelf": boolean;

    /**
     * new ports are allowed by the firewall
     */
    "newPorts": boolean;

    /**
     * stop listening on the port of this session
     */
    "removeCurrentPort": boolean;

    /**
     * AllowUsers/AllowGroups exclude the login user
     */
    "lockout": boolean;
}

/**
 * SSHUpdate sets directives: keyword (case-insensitive) → values. An empty
 * list removes the app's directive (the server default or other files apply).
 */
export interface SSHUpdate {
    "set": { [_ in string]?: string[] | null } | null;
    "confirm": SSHConfirm;
}

export interface SSHUpdateResult {
    "config": SSHConfig;

    /**
     * Overridden lists directives whose effective value differs from what
     * was written (another file wins).
     */
    "overridden": string[] | null;

    /**
     * Listening are the ports sshd listens on after the reload.
     */
    "listening": number[] | null;
    "reloaded": boolean;
    "backup": string;
}

export interface SudoEvent {
    "time": number;
    "user": string;
    "runAs": string;
    "command": string;
    "cwd": string;
    "tty": string;
    "failed": boolean;
    "reason": string;

    /**
     * App: most likely run by Server Manager itself (sh -c by the login user).
     */
    "app": boolean;
}

export interface UFWPolicy {
    "incoming": string;
    "outgoing": string;
    "routed": string;
}

export interface UFWRule {
    "num": number;
    "to": string;

    /**
     * ALLOW | DENY | REJECT | LIMIT
     */
    "action": string;

    /**
     * IN | OUT | FWD
     */
    "direction": string;
    "from": string;
    "comment": string;
    "v6": boolean;

    /**
     * the line as shown (used to confirm deletes)
     */
    "raw": string;
}

export interface UFWStatus {
    "installed": boolean;
    "active": boolean;
    "logging": string;
    "defaults": UFWPolicy;
    "rules": UFWRule[] | null;

    /**
     * Added lists `ufw show added` commands (inactive firewall).
     */
    "added": string[] | null;
    "sshPorts": number[] | null;
    "clientIp": string;
}

export interface UsersResult {
    "users": LinuxUser[] | null;
    "groups": LinuxGroup[] | null;
    "shells": string[] | null;
    "adminGroups": string[] | null;
    "loginUser": string;
    "busybox": boolean;

    /**
     * no root: password status unknown
     */
    "limited": boolean;
    "uidMin": number;
}
