// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AccessAllow allowlists addresses: on every port, the SSH ports or given
 * ports. Allow rules go before block rules; fail2ban also ignores them.
 */
export function AccessAllow(connID: string, req: $models.AccessRequest, sudoPassword: string): $CancellablePromise<$models.AccessResult> {
    return $Call.ByID(2074516970, connID, req, sudoPassword);
}

/**
 * AccessBlock blocks addresses: a firewall rule placed before every allow
 * rule, or (Temporary) a fail2ban ban that expires.
 */
export function AccessBlock(connID: string, req: $models.AccessRequest, sudoPassword: string): $CancellablePromise<$models.AccessResult> {
    return $Call.ByID(4019230938, connID, req, sudoPassword);
}

/**
 * AccessList returns every blocked/allowed address and the fail2ban setup.
 */
export function AccessList(connID: string, sudoPassword: string): $CancellablePromise<$models.AccessState> {
    return $Call.ByID(2429755929, connID, sudoPassword);
}

/**
 * AccessRemove removes block/allow entries (as listed by AccessList).
 * Removing an allow entry that the current session relies on while SSH is
 * locked to the allowlist needs force.
 */
export function AccessRemove(connID: string, entries: $models.AccessEntry[] | null, force: boolean, sudoPassword: string): $CancellablePromise<$models.AccessResult> {
    return $Call.ByID(651285781, connID, entries, force, sudoPassword);
}

/**
 * AccessSSHLock makes SSH reachable only from allowlisted addresses (lock)
 * or from everywhere again (unlock). Locking requires that the current
 * session's address is allowlisted for SSH and that the firewall filters.
 */
export function AccessSSHLock(connID: string, lock: boolean, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(3938226086, connID, lock, sudoPassword);
}

/**
 * AddGroup creates a group.
 */
export function AddGroup(connID: string, name: string, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(4014050269, connID, name, sudoPassword);
}

/**
 * AddKey appends a public key to user's authorized_keys ("" = login user).
 */
export function AddKey(connID: string, user: string, key: string, sudoPassword: string): $CancellablePromise<$models.AuthorizedKey> {
    return $Call.ByID(3595947425, connID, user, key, sudoPassword);
}

/**
 * AddUser creates an account; on a failure after creation it is removed again.
 */
export function AddUser(connID: string, req: $models.NewUser, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(2345342477, connID, req, sudoPassword);
}

/**
 * AllowPort opens an incoming port on the primary firewall (ufw rule,
 * firewalld default zone, or iptables INPUT). Returns the backend used.
 */
export function AllowPort(connID: string, port: number, proto: string, comment: string, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(2589859347, connID, port, proto, comment, sudoPassword);
}

/**
 * CheckPort reports whether incoming port/proto is allowed by the active firewall.
 */
export function CheckPort(connID: string, port: number, proto: string, sudoPassword: string): $CancellablePromise<$models.PortCheck> {
    return $Call.ByID(144471650, connID, port, proto, sudoPassword);
}

/**
 * DeleteGroup deletes a non-system group that is nobody's primary group.
 */
export function DeleteGroup(connID: string, name: string, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(1236756191, connID, name, sudoPassword);
}

/**
 * DeleteUser removes an account (optionally its home). Refuses root, UID 0
 * accounts, system accounts and the account the app is connected as.
 */
export function DeleteUser(connID: string, name: string, removeHome: boolean, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(1172258607, connID, name, removeHome, sudoPassword);
}

/**
 * Events collects security events of the last `hours` hours (1..720).
 */
export function Events(connID: string, hours: number, sudoPassword: string): $CancellablePromise<$models.EventsResult> {
    return $Call.ByID(1549193658, connID, hours, sudoPassword);
}

/**
 * Fail2banApply writes the app's jail file (sshd jail, ban policy, ignore
 * list, recidive), checks the configuration and (re)starts fail2ban. On
 * failure the previous file is restored.
 */
export function Fail2banApply(connID: string, cfg: $models.Fail2banConfig, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(1601211044, connID, cfg, sudoPassword);
}

/**
 * Fail2banInstall installs fail2ban with the package manager (job). It is
 * configured and started afterwards with Fail2banApply.
 */
export function Fail2banInstall(connID: string, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(1359150739, connID, sudoPassword);
}

/**
 * Fail2banSetBan bans or unbans an IP in a fail2ban jail. Banning the
 * address of this session is refused.
 */
export function Fail2banSetBan(connID: string, jail: string, ip: string, ban: boolean, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(2790997457, connID, jail, ip, ban, sudoPassword);
}

/**
 * Fail2banSetRunning starts (and enables at boot) or stops fail2ban.
 */
export function Fail2banSetRunning(connID: string, on: boolean, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(1044995167, connID, on, sudoPassword);
}

/**
 * FirewallDetect reports which firewall tools exist and which is active.
 */
export function FirewallDetect(connID: string, sudoPassword: string): $CancellablePromise<$models.FirewallInfo> {
    return $Call.ByID(3110511480, connID, sudoPassword);
}

/**
 * FirewalldChange adds or removes a port ("80/tcp", "8000-8100/udp"),
 * service, rich rule or source in a zone, permanently, then reloads.
 */
export function FirewalldChange(connID: string, zone: string, kind: string, value: string, add: boolean, force: boolean, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(2705770177, connID, zone, kind, value, add, force, sudoPassword);
}

/**
 * FirewalldStatus reads firewalld zones and their rules.
 */
export function FirewalldStatus(connID: string, sudoPassword: string): $CancellablePromise<$models.FirewalldStatus> {
    return $Call.ByID(3302108803, connID, sudoPassword);
}

/**
 * IptablesAddRule adds a simple rule to a built-in chain. Rules are not
 * persistent until IptablesSave.
 */
export function IptablesAddRule(connID: string, rule: $models.NewIptRule, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(3657711368, connID, rule, sudoPassword);
}

/**
 * IptablesDeleteRule deletes rule num of chain after checking its spec is
 * still expect.
 */
export function IptablesDeleteRule(connID: string, v6: boolean, chain: string, num: number, expect: string, force: boolean, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(1695779750, connID, v6, chain, num, expect, force, sudoPassword);
}

/**
 * IptablesSave persists the current rules; returns the method used.
 */
export function IptablesSave(connID: string, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(2681899302, connID, sudoPassword);
}

/**
 * IptablesStatus lists the filter table's built-in chains (v6 = ip6tables).
 */
export function IptablesStatus(connID: string, v6: boolean, sudoPassword: string): $CancellablePromise<$models.IptablesStatus> {
    return $Call.ByID(3898561405, connID, v6, sudoPassword);
}

/**
 * ListKeys lists the authorized keys of user ("" = the login user).
 */
export function ListKeys(connID: string, user: string, sudoPassword: string): $CancellablePromise<$models.KeyList> {
    return $Call.ByID(533853703, connID, user, sudoPassword);
}

/**
 * NftRuleset returns `nft list ruleset` (read-only view).
 */
export function NftRuleset(connID: string, sudoPassword: string): $CancellablePromise<string> {
    return $Call.ByID(4128388653, connID, sudoPassword);
}

/**
 * OpenPorts lists listening TCP/UDP sockets. With useSudo the process of
 * every socket is shown; without, only the login user's.
 */
export function OpenPorts(connID: string, useSudo: boolean, sudoPassword: string): $CancellablePromise<$models.PortsResult> {
    return $Call.ByID(1931992301, connID, useSudo, sudoPassword);
}

/**
 * Overview runs the security checklist and computes a score.
 */
export function Overview(connID: string, sudoPassword: string): $CancellablePromise<$models.Overview> {
    return $Call.ByID(4022894952, connID, sudoPassword);
}

/**
 * RemoveKey removes every line with the given fingerprint. It refuses the
 * key the current session authenticated with, and removing the last key
 * while sshd has password login disabled unless confirmLast is set.
 */
export function RemoveKey(connID: string, user: string, fingerprint: string, confirmLast: boolean, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(4233394378, connID, user, fingerprint, confirmLast, sudoPassword);
}

/**
 * SSHConfig reads the effective sshd configuration.
 */
export function SSHConfig(connID: string, sudoPassword: string): $CancellablePromise<$models.SSHConfig> {
    return $Call.ByID(1740796533, connID, sudoPassword);
}

/**
 * SetGroups adds/removes supplementary groups. Removing the login user from
 * its last admin group requires force.
 */
export function SetGroups(connID: string, name: string, add: string[] | null, remove: string[] | null, force: boolean, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(2523996413, connID, name, add, remove, force, sudoPassword);
}

/**
 * SetLocked locks or unlocks an account's password (usermod -L/-U). Key
 * logins keep working while locked.
 */
export function SetLocked(connID: string, name: string, locked: boolean, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(2447509539, connID, name, locked, sudoPassword);
}

/**
 * SetPassword sets an account's password (fed on stdin to chpasswd).
 */
export function SetPassword(connID: string, name: string, password: string, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(3646943880, connID, name, password, sudoPassword);
}

/**
 * UFWAddRule adds a ufw rule.
 */
export function UFWAddRule(connID: string, rule: $models.NewUFWRule, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(1020376354, connID, rule, sudoPassword);
}

/**
 * UFWDeleteAdded deletes a rule of an inactive ufw by its `ufw show added`
 * line (which must still be listed). No SSH guard is needed: enabling ufw
 * always allows the SSH ports first.
 */
export function UFWDeleteAdded(connID: string, line: string, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(199251296, connID, line, sudoPassword);
}

/**
 * UFWDeleteRule deletes rule num after checking it still is the rule the
 * user saw (expect = its Raw text).
 */
export function UFWDeleteRule(connID: string, num: number, expect: string, force: boolean, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(4287035764, connID, num, expect, force, sudoPassword);
}

/**
 * UFWDisable turns ufw off (rules are kept).
 */
export function UFWDisable(connID: string, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(2339514731, connID, sudoPassword);
}

/**
 * UFWEnable allows the SSH port(s) first, then enables ufw. Returns the
 * SSH rules that were ensured ("22/tcp").
 */
export function UFWEnable(connID: string, sudoPassword: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(213496134, connID, sudoPassword);
}

/**
 * UFWReload reloads ufw's rules.
 */
export function UFWReload(connID: string, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(625529348, connID, sudoPassword);
}

/**
 * UFWReset disables ufw and deletes all rules (ufw keeps a backup).
 */
export function UFWReset(connID: string, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(1986379368, connID, sudoPassword);
}

/**
 * UFWSetDefault sets a default policy (direction incoming|outgoing|routed,
 * policy allow|deny|reject). Before denying incoming traffic on an active
 * firewall the SSH ports are allowed.
 */
export function UFWSetDefault(connID: string, direction: string, policy: string, sudoPassword: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(145355964, connID, direction, policy, sudoPassword);
}

/**
 * UFWSetLogging sets ufw's log level.
 */
export function UFWSetLogging(connID: string, level: string, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(944952068, connID, level, sudoPassword);
}

/**
 * UFWStatus reads ufw's state, defaults and rules.
 */
export function UFWStatus(connID: string, sudoPassword: string): $CancellablePromise<$models.UFWStatus> {
    return $Call.ByID(1597832167, connID, sudoPassword);
}

/**
 * UpdateSSH changes sshd settings safely: guards against locking the app
 * out, writes the drop-in/managed block, validates with `sshd -t` (restoring
 * the previous files on failure) and reloads sshd.
 */
export function UpdateSSH(connID: string, req: $models.SSHUpdate, sudoPassword: string): $CancellablePromise<$models.SSHUpdateResult> {
    return $Call.ByID(3171329420, connID, req, sudoPassword);
}

/**
 * Users lists Linux accounts and groups.
 */
export function Users(connID: string, sudoPassword: string): $CancellablePromise<$models.UsersResult> {
    return $Call.ByID(2756299613, connID, sudoPassword);
}
