// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExecResult is the outcome of a non-interactive command.
 */
export interface ExecResult {
    "stdout": string;
    "stderr": string;
    "exitCode": number;
}
