// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Active lists the deployments running on this server.
 */
export function Active(connID: string): $CancellablePromise<$models.DeployStart[] | null> {
    return $Call.ByID(3578549515, connID);
}

/**
 * Apps lists the server's applications with their deployment state.
 */
export function Apps(connID: string): $CancellablePromise<$models.AppView[] | null> {
    return $Call.ByID(652718929, connID);
}

/**
 * DeleteApp removes an application, its secrets and history (files on the
 * server are left alone).
 */
export function DeleteApp(connID: string, appID: string): $CancellablePromise<void> {
    return $Call.ByID(2623012037, connID, appID);
}

/**
 * Deploy starts a deployment job. The job id and run id are returned; the
 * pipeline reports progress with "deploy:step" events.
 */
export function Deploy(connID: string, appID: string, opts: $models.DeployOptions, sudoPassword: string): $CancellablePromise<$models.DeployStart> {
    return $Call.ByID(1888060418, connID, appID, opts, sudoPassword);
}

/**
 * GetApp returns one application.
 */
export function GetApp(connID: string, appID: string): $CancellablePromise<$models.AppView> {
    return $Call.ByID(1410758030, connID, appID);
}

/**
 * ReleaseLock force-removes the app's remote deploy lock (left by a crashed
 * or disconnected app instance). Refused while this instance deploys it.
 */
export function ReleaseLock(connID: string, appID: string, sudoPassword: string): $CancellablePromise<void> {
    return $Call.ByID(4079136709, connID, appID, sudoPassword);
}

/**
 * RemoteRefs lists the repository's branches and tags (for the deploy dialog).
 */
export function RemoteRefs(connID: string, appID: string, sudoPassword: string): $CancellablePromise<$models.GitRef[] | null> {
    return $Call.ByID(3017700441, connID, appID, sudoPassword);
}

/**
 * Rollback redeploys the version of a successful run: runID, or "" for the
 * previous successful version.
 */
export function Rollback(connID: string, appID: string, runID: string, sudoPassword: string): $CancellablePromise<$models.DeployStart> {
    return $Call.ByID(1047479497, connID, appID, runID, sudoPassword);
}

/**
 * RunDetail returns one deployment with its log.
 */
export function RunDetail(connID: string, runID: string): $CancellablePromise<$models.RunDetail> {
    return $Call.ByID(1253672567, connID, runID);
}

/**
 * Runs lists an application's deployments, newest first.
 */
export function Runs(connID: string, appID: string, limit: number): $CancellablePromise<$models.Run[] | null> {
    return $Call.ByID(3563685247, connID, appID, limit);
}

/**
 * SaveApp creates or updates an application, its secrets and git token.
 */
export function SaveApp(connID: string, $in: $models.SaveAppInput): $CancellablePromise<$models.AppView> {
    return $Call.ByID(243345567, connID, $in);
}
