// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apperr$0 from "../../internal/apperr/models.js";

/**
 * App is a deployable application on one server.
 */
export interface App {
    "id": string;
    "server": string;
    "name": string;

    /**
     * Stage: production | staging | development.
     */
    "stage": string;
    "type": string;

    /**
     * Dir is the deploy directory: the git checkout, or the compose project dir.
     */
    "dir": string;

    /**
     * EnvFile is where variables and secrets are written ("" = <dir>/.env;
     * relative paths are relative to Dir).
     */
    "envFile": string;

    /**
     * LoadEnv exports the env file's variables into build/test/restart/health commands.
     */
    "loadEnv": boolean;

    /**
     * Sudo runs every step as root; RestartSudo only the restart command.
     */
    "sudo": boolean;
    "restartSudo": boolean;

    /**
     * git
     */
    "repo": string;

    /**
     * default branch or tag to deploy
     */
    "branch": string;

    /**
     * username sent with the HTTPS token
     */
    "tokenUser": string;

    /**
     * output only
     */
    "hasToken": boolean;
    "submodules": boolean;

    /**
     * Multi-line shell scripts, run in Dir with `set -e`.
     */
    "buildCmd": string;
    "testCmd": string;
    "restartCmd": string;

    /**
     * compose / image
     * relative to Dir (default compose.yml)
     */
    "composeFile": string;

    /**
     * compose project name ("" = compose default)
     */
    "project": string;

    /**
     * env var holding the image tag
     */
    "tagVar": string;
    "defaultTag": string;

    /**
     * images are built/loaded locally
     */
    "skipPull": boolean;
    "image": ImageSpec;
    "vars": EnvVar[] | null;

    /**
     * names only; values live in the keychain
     */
    "secrets": string[] | null;
    "health": HealthCheck;
    "autoRollback": boolean;

    /**
     * Advanced
     * preflight disk-space floor
     */
    "minFreeMB": number;

    /**
     * minutes per build/test/restart step
     */
    "commandTimeout": number;
    "created": number;
    "updated": number;
}

/**
 * AppView is an app with its deployment state.
 */
export interface AppView {
    "app": App;

    /**
     * Current is the last successful deployment (what is live).
     */
    "current": Run | null;

    /**
     * Last is the most recent deployment, whatever its outcome.
     */
    "last": Run | null;

    /**
     * Active is set while a deployment runs.
     */
    "active": DeployStart | null;
}

/**
 * Commit describes the deployed git commit.
 */
export interface Commit {
    "sha": string;
    "short": string;
    "subject": string;
    "author": string;

    /**
     * unix s
     */
    "time": number;
}

/**
 * DeployOptions chooses what to deploy.
 */
export interface DeployOptions {
    /**
     * Ref: git branch, tag or commit sha; or the image tag. "" = the app's
     * default branch / tag.
     */
    "ref": string;

    /**
     * RedeployOf: deploy exactly the version of this earlier run.
     */
    "redeployOf": string;
}

/**
 * DeployStart identifies a started deployment.
 */
export interface DeployStart {
    "jobId": string;
    "runId": string;
    "appId": string;
}

/**
 * EnvVar is a plain (non-secret) environment variable.
 */
export interface EnvVar {
    "name": string;
    "value": string;
}

/**
 * GitRef is a branch or tag of the remote repository.
 */
export interface GitRef {
    "name": string;

    /**
     * branch | tag
     */
    "kind": string;
    "sha": string;
}

/**
 * HealthCheck runs after the restart step.
 */
export interface HealthCheck {
    /**
     * none | http | command
     */
    "type": string;

    /**
     * http: checked from the server with curl or wget.
     */
    "url": string;

    /**
     * 0 = any 2xx/3xx
     */
    "expectStatus": number;
    "bodyContains": string;

    /**
     * skip TLS verification
     */
    "insecure": boolean;

    /**
     * command: exit 0 = healthy.
     */
    "command": string;

    /**
     * seconds per attempt
     */
    "timeout": number;

    /**
     * attempts
     */
    "retries": number;

    /**
     * seconds between attempts
     */
    "interval": number;

    /**
     * seconds before the first attempt
     */
    "delay": number;
}

/**
 * ImageSpec describes the container of a TypeImage app.
 */
export interface ImageSpec {
    /**
     * without tag, e.g. "ghcr.io/org/app"
     */
    "image": string;
    "containerName": string;

    /**
     * "8080:80", "127.0.0.1:8080:80/tcp"
     */
    "ports": string[] | null;

    /**
     * "./data:/data", "name:/path:ro"
     */
    "volumes": string[] | null;

    /**
     * no | always | unless-stopped | on-failure
     */
    "restart": string;

    /**
     * optional command override (sh -c)
     */
    "command": string;

    /**
     * Optional Docker HEALTHCHECK (CMD-SHELL).
     */
    "healthCmd": string;

    /**
     * seconds
     */
    "healthInterval": number;
    "healthTimeout": number;
    "healthRetries": number;
}

/**
 * Run is a deployment in the history (without its log).
 */
export interface Run {
    "id": string;
    "appId": string;
    "server": string;

    /**
     * unix ms
     */
    "started": number;

    /**
     * unix ms, 0 while running
     */
    "finished": number;

    /**
     * running | ok | failed | cancelled | interrupted
     */
    "status": string;
    "actor": string;
    "version": string;
    "data": RunData;
}

/**
 * RunData is stored as JSON in runs.data.
 */
export interface RunData {
    "appName": string;
    "appType": string;

    /**
     * Trigger: manual | redeploy | rollback | auto-rollback.
     */
    "trigger": string;

    /**
     * run id this rollback undoes (auto) or the run whose version it restores (manual)
     */
    "rollbackOf": string;

    /**
     * Ref is what was asked for (branch, tag, sha or image tag); RefKind is
     * branch | tag | commit | image.
     */
    "ref": string;
    "refKind": string;
    "branch": string;

    /**
     * full sha or image tag actually deployed
     */
    "target": string;
    "commit": Commit | null;

    /**
     * What was deployed before this run.
     */
    "previousVersion": string;
    "previousTarget": string;
    "steps": Step[] | null;
    "error": apperr$0.Error | null;
    "jobId": string;

    /**
     * Set on a failed run that was automatically rolled back.
     */
    "rolledBackBy": string;
}

/**
 * RunDetail is a run with its stored (redacted) log.
 */
export interface RunDetail {
    "run": Run;
    "log": string;
}

/**
 * SaveAppInput is the editor's payload. Secret values and the token are
 * write-only: they are stored in the OS keychain and never returned.
 */
export interface SaveAppInput {
    "app": App;
    "secrets": SecretChange[] | null;

    /**
     * TokenAction: "" / "keep" | "set" | "remove".
     */
    "tokenAction": string;
    "token": string;
}

/**
 * SecretChange sets (Value) or removes a secret.
 */
export interface SecretChange {
    "name": string;
    "value": string;
    "remove": boolean;
}

/**
 * Step is one stage of a deployment.
 */
export interface Step {
    "id": string;
    "state": string;

    /**
     * unix ms
     */
    "startedAt": number;

    /**
     * unix ms
     */
    "finishedAt": number;
    "note": string;
}

/**
 * StepEvent is the payload of "deploy:step".
 */
export interface StepEvent {
    "server": string;
    "appId": string;
    "jobId": string;
    "runId": string;
    "step": string;
    "state": string;
    "startedAt": number;
    "finishedAt": number;
    "note": string;
}
